// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: crypto.proto

package icrypto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// macOS 计算镜像偏好，不改变对外声明的设备系统版本。
type MacOSRuntime int32

const (
	MacOSRuntime_MACOS_AUTO       MacOSRuntime = 0
	MacOSRuntime_MACOS_COMPATIBLE MacOSRuntime = 1
)

// Enum value maps for MacOSRuntime.
var (
	MacOSRuntime_name = map[int32]string{
		0: "MACOS_AUTO",
		1: "MACOS_COMPATIBLE",
	}
	MacOSRuntime_value = map[string]int32{
		"MACOS_AUTO":       0,
		"MACOS_COMPATIBLE": 1,
	}
)

func (x MacOSRuntime) Enum() *MacOSRuntime {
	p := new(MacOSRuntime)
	*p = x
	return p
}

func (x MacOSRuntime) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MacOSRuntime) Descriptor() protoreflect.EnumDescriptor {
	return file_crypto_proto_enumTypes[0].Descriptor()
}

func (MacOSRuntime) Type() protoreflect.EnumType {
	return &file_crypto_proto_enumTypes[0]
}

func (x MacOSRuntime) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MacOSRuntime.Descriptor instead.
func (MacOSRuntime) EnumDescriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{0}
}

// 只选择本次传统激活签名的实现，不改变 ADI/Validation 会话。
type ActivationSigningProfile int32

const (
	ActivationSigningProfile_ACTIVATION_SIGNING_CURRENT     ActivationSigningProfile = 0
	ActivationSigningProfile_ACTIVATION_SIGNING_LEGACY_IOS9 ActivationSigningProfile = 1
)

// Enum value maps for ActivationSigningProfile.
var (
	ActivationSigningProfile_name = map[int32]string{
		0: "ACTIVATION_SIGNING_CURRENT",
		1: "ACTIVATION_SIGNING_LEGACY_IOS9",
	}
	ActivationSigningProfile_value = map[string]int32{
		"ACTIVATION_SIGNING_CURRENT":     0,
		"ACTIVATION_SIGNING_LEGACY_IOS9": 1,
	}
)

func (x ActivationSigningProfile) Enum() *ActivationSigningProfile {
	p := new(ActivationSigningProfile)
	*p = x
	return p
}

func (x ActivationSigningProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivationSigningProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_crypto_proto_enumTypes[1].Descriptor()
}

func (ActivationSigningProfile) Type() protoreflect.EnumType {
	return &file_crypto_proto_enumTypes[1]
}

func (x ActivationSigningProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivationSigningProfile.Descriptor instead.
func (ActivationSigningProfile) EnumDescriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{1}
}

// 初始化参数分离 DRM 能力和 macOS 镜像偏好，不能再按位组合。
type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        []byte                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	IosDrm        bool                   `protobuf:"varint,4,opt,name=ios_drm,json=iosDrm,proto3" json:"ios_drm,omitempty"`
	MacosRuntime  MacOSRuntime           `protobuf:"varint,5,opt,name=macos_runtime,json=macosRuntime,proto3,enum=icrypto.MacOSRuntime" json:"macos_runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeRequest) GetDevice() []byte {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *InitializeRequest) GetIosDrm() bool {
	if x != nil {
		return x.IosDrm
	}
	return false
}

func (x *InitializeRequest) GetMacosRuntime() MacOSRuntime {
	if x != nil {
		return x.MacosRuntime
	}
	return MacOSRuntime_MACOS_AUTO
}

// 初始化响应
type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        []byte                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeResponse) GetDevice() []byte {
	if x != nil {
		return x.Device
	}
	return nil
}

// 同步已初始化 cryptor 使用的设备状态。
//
// Initialize 可能先从真实硬件补全设备标识，调用方随后才取得依赖这些
// 标识的票据。该 RPC 只合并设备数据，不重建 VM、SEP 或 guest session。
type SyncDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        []byte                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDeviceRequest) Reset() {
	*x = SyncDeviceRequest{}
	mi := &file_crypto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDeviceRequest) ProtoMessage() {}

func (x *SyncDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDeviceRequest.ProtoReflect.Descriptor instead.
func (*SyncDeviceRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{2}
}

func (x *SyncDeviceRequest) GetDevice() []byte {
	if x != nil {
		return x.Device
	}
	return nil
}

type SyncDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDeviceResponse) Reset() {
	*x = SyncDeviceResponse{}
	mi := &file_crypto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDeviceResponse) ProtoMessage() {}

func (x *SyncDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDeviceResponse.ProtoReflect.Descriptor instead.
func (*SyncDeviceResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{3}
}

// 结束请求
type FinalizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeRequest) Reset() {
	*x = FinalizeRequest{}
	mi := &file_crypto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeRequest) ProtoMessage() {}

func (x *FinalizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeRequest.ProtoReflect.Descriptor instead.
func (*FinalizeRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{4}
}

// 结束响应
type FinalizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeResponse) Reset() {
	*x = FinalizeResponse{}
	mi := &file_crypto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeResponse) ProtoMessage() {}

func (x *FinalizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeResponse.ProtoReflect.Descriptor instead.
func (*FinalizeResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{5}
}

// DRM 激活握手请求
type ActivationDRMHandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivationDRMHandshakeRequest) Reset() {
	*x = ActivationDRMHandshakeRequest{}
	mi := &file_crypto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDRMHandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDRMHandshakeRequest) ProtoMessage() {}

func (x *ActivationDRMHandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDRMHandshakeRequest.ProtoReflect.Descriptor instead.
func (*ActivationDRMHandshakeRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{6}
}

// DRM 激活握手响应
type ActivationDRMHandshakeResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	CollectionBlob          []byte                 `protobuf:"bytes,1,opt,name=collection_blob,json=collectionBlob,proto3" json:"collection_blob,omitempty"`
	HandshakeRequestMessage []byte                 `protobuf:"bytes,2,opt,name=handshake_request_message,json=handshakeRequestMessage,proto3" json:"handshake_request_message,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ActivationDRMHandshakeResponse) Reset() {
	*x = ActivationDRMHandshakeResponse{}
	mi := &file_crypto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDRMHandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDRMHandshakeResponse) ProtoMessage() {}

func (x *ActivationDRMHandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDRMHandshakeResponse.ProtoReflect.Descriptor instead.
func (*ActivationDRMHandshakeResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{7}
}

func (x *ActivationDRMHandshakeResponse) GetCollectionBlob() []byte {
	if x != nil {
		return x.CollectionBlob
	}
	return nil
}

func (x *ActivationDRMHandshakeResponse) GetHandshakeRequestMessage() []byte {
	if x != nil {
		return x.HandshakeRequestMessage
	}
	return nil
}

// DRM 激活处理请求
type ActivationDRMProcessRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SUInfo                   []byte                 `protobuf:"bytes,1,opt,name=SUInfo,proto3" json:"SUInfo,omitempty"`
	HandshakeResponseMessage []byte                 `protobuf:"bytes,2,opt,name=handshake_response_message,json=handshakeResponseMessage,proto3" json:"handshake_response_message,omitempty"`
	ServerKP                 []byte                 `protobuf:"bytes,3,opt,name=serverKP,proto3" json:"serverKP,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ActivationDRMProcessRequest) Reset() {
	*x = ActivationDRMProcessRequest{}
	mi := &file_crypto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDRMProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDRMProcessRequest) ProtoMessage() {}

func (x *ActivationDRMProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDRMProcessRequest.ProtoReflect.Descriptor instead.
func (*ActivationDRMProcessRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{8}
}

func (x *ActivationDRMProcessRequest) GetSUInfo() []byte {
	if x != nil {
		return x.SUInfo
	}
	return nil
}

func (x *ActivationDRMProcessRequest) GetHandshakeResponseMessage() []byte {
	if x != nil {
		return x.HandshakeResponseMessage
	}
	return nil
}

func (x *ActivationDRMProcessRequest) GetServerKP() []byte {
	if x != nil {
		return x.ServerKP
	}
	return nil
}

// DRM 激活处理响应
type ActivationDRMProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UIK           []byte                 `protobuf:"bytes,1,opt,name=UIK,proto3" json:"UIK,omitempty"`
	RK            []byte                 `protobuf:"bytes,2,opt,name=RK,proto3" json:"RK,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivationDRMProcessResponse) Reset() {
	*x = ActivationDRMProcessResponse{}
	mi := &file_crypto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDRMProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDRMProcessResponse) ProtoMessage() {}

func (x *ActivationDRMProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDRMProcessResponse.ProtoReflect.Descriptor instead.
func (*ActivationDRMProcessResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{9}
}

func (x *ActivationDRMProcessResponse) GetUIK() []byte {
	if x != nil {
		return x.UIK
	}
	return nil
}

func (x *ActivationDRMProcessResponse) GetRK() []byte {
	if x != nil {
		return x.RK
	}
	return nil
}

// DRM 激活签名请求
type ActivationDRMSignatureRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActivationInfoXml []byte                 `protobuf:"bytes,1,opt,name=activation_info_xml,json=activationInfoXml,proto3" json:"activation_info_xml,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActivationDRMSignatureRequest) Reset() {
	*x = ActivationDRMSignatureRequest{}
	mi := &file_crypto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDRMSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDRMSignatureRequest) ProtoMessage() {}

func (x *ActivationDRMSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDRMSignatureRequest.ProtoReflect.Descriptor instead.
func (*ActivationDRMSignatureRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{10}
}

func (x *ActivationDRMSignatureRequest) GetActivationInfoXml() []byte {
	if x != nil {
		return x.ActivationInfoXml
	}
	return nil
}

// DRM 激活签名响应
type ActivationDRMSignatureResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FairplayCertChain []byte                 `protobuf:"bytes,1,opt,name=fairplay_cert_chain,json=fairplayCertChain,proto3" json:"fairplay_cert_chain,omitempty"`
	FairplaySignature []byte                 `protobuf:"bytes,2,opt,name=fairplay_signature,json=fairplaySignature,proto3" json:"fairplay_signature,omitempty"`
	RKSignature       []byte                 `protobuf:"bytes,3,opt,name=RKSignature,proto3" json:"RKSignature,omitempty"`
	SignActRequest    []byte                 `protobuf:"bytes,4,opt,name=sign_act_request,json=signActRequest,proto3" json:"sign_act_request,omitempty"`
	ServerKP          []byte                 `protobuf:"bytes,5,opt,name=serverKP,proto3" json:"serverKP,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActivationDRMSignatureResponse) Reset() {
	*x = ActivationDRMSignatureResponse{}
	mi := &file_crypto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDRMSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDRMSignatureResponse) ProtoMessage() {}

func (x *ActivationDRMSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDRMSignatureResponse.ProtoReflect.Descriptor instead.
func (*ActivationDRMSignatureResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{11}
}

func (x *ActivationDRMSignatureResponse) GetFairplayCertChain() []byte {
	if x != nil {
		return x.FairplayCertChain
	}
	return nil
}

func (x *ActivationDRMSignatureResponse) GetFairplaySignature() []byte {
	if x != nil {
		return x.FairplaySignature
	}
	return nil
}

func (x *ActivationDRMSignatureResponse) GetRKSignature() []byte {
	if x != nil {
		return x.RKSignature
	}
	return nil
}

func (x *ActivationDRMSignatureResponse) GetSignActRequest() []byte {
	if x != nil {
		return x.SignActRequest
	}
	return nil
}

func (x *ActivationDRMSignatureResponse) GetServerKP() []byte {
	if x != nil {
		return x.ServerKP
	}
	return nil
}

// 一次性签名：不要求 Initialize，不写回设备，不占用调用方现有会话。
type ActivationSignRequest struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	Profile           ActivationSigningProfile `protobuf:"varint,1,opt,name=profile,proto3,enum=icrypto.ActivationSigningProfile" json:"profile,omitempty"`
	MacosRuntime      MacOSRuntime             `protobuf:"varint,5,opt,name=macos_runtime,json=macosRuntime,proto3,enum=icrypto.MacOSRuntime" json:"macos_runtime,omitempty"`
	Device            []byte                   `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	ActivationInfoXml []byte                   `protobuf:"bytes,4,opt,name=activation_info_xml,json=activationInfoXml,proto3" json:"activation_info_xml,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActivationSignRequest) Reset() {
	*x = ActivationSignRequest{}
	mi := &file_crypto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationSignRequest) ProtoMessage() {}

func (x *ActivationSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationSignRequest.ProtoReflect.Descriptor instead.
func (*ActivationSignRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{12}
}

func (x *ActivationSignRequest) GetProfile() ActivationSigningProfile {
	if x != nil {
		return x.Profile
	}
	return ActivationSigningProfile_ACTIVATION_SIGNING_CURRENT
}

func (x *ActivationSignRequest) GetMacosRuntime() MacOSRuntime {
	if x != nil {
		return x.MacosRuntime
	}
	return MacOSRuntime_MACOS_AUTO
}

func (x *ActivationSignRequest) GetDevice() []byte {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *ActivationSignRequest) GetActivationInfoXml() []byte {
	if x != nil {
		return x.ActivationInfoXml
	}
	return nil
}

// 旧版激活请求
type ActivationDeprecatedRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActivationInfoXml []byte                 `protobuf:"bytes,1,opt,name=activation_info_xml,json=activationInfoXml,proto3" json:"activation_info_xml,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActivationDeprecatedRequest) Reset() {
	*x = ActivationDeprecatedRequest{}
	mi := &file_crypto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDeprecatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDeprecatedRequest) ProtoMessage() {}

func (x *ActivationDeprecatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDeprecatedRequest.ProtoReflect.Descriptor instead.
func (*ActivationDeprecatedRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{13}
}

func (x *ActivationDeprecatedRequest) GetActivationInfoXml() []byte {
	if x != nil {
		return x.ActivationInfoXml
	}
	return nil
}

// 旧版激活响应
type ActivationDeprecatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sign          []byte                 `protobuf:"bytes,1,opt,name=sign,proto3" json:"sign,omitempty"`
	Cert          []byte                 `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivationDeprecatedResponse) Reset() {
	*x = ActivationDeprecatedResponse{}
	mi := &file_crypto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDeprecatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDeprecatedResponse) ProtoMessage() {}

func (x *ActivationDeprecatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDeprecatedResponse.ProtoReflect.Descriptor instead.
func (*ActivationDeprecatedResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{14}
}

func (x *ActivationDeprecatedResponse) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (x *ActivationDeprecatedResponse) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

// 激活记录请求
type ActivationRecordRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Unbrick                 bool                   `protobuf:"varint,1,opt,name=unbrick,proto3" json:"unbrick,omitempty"`
	AccountTokenCertificate []byte                 `protobuf:"bytes,2,opt,name=account_token_certificate,json=accountTokenCertificate,proto3" json:"account_token_certificate,omitempty"`
	DeviceCertificate       []byte                 `protobuf:"bytes,3,opt,name=device_certificate,json=deviceCertificate,proto3" json:"device_certificate,omitempty"`
	RegulatoryInfo          []byte                 `protobuf:"bytes,4,opt,name=regulatory_info,json=regulatoryInfo,proto3" json:"regulatory_info,omitempty"`
	FairplayKeyData         []byte                 `protobuf:"bytes,5,opt,name=fairplay_key_data,json=fairplayKeyData,proto3" json:"fairplay_key_data,omitempty"`
	AccountToken            []byte                 `protobuf:"bytes,6,opt,name=account_token,json=accountToken,proto3" json:"account_token,omitempty"`
	AccountTokenSignature   []byte                 `protobuf:"bytes,7,opt,name=account_token_signature,json=accountTokenSignature,proto3" json:"account_token_signature,omitempty"`
	UniqueDeviceCertificate []byte                 `protobuf:"bytes,8,opt,name=unique_device_certificate,json=uniqueDeviceCertificate,proto3" json:"unique_device_certificate,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ActivationRecordRequest) Reset() {
	*x = ActivationRecordRequest{}
	mi := &file_crypto_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationRecordRequest) ProtoMessage() {}

func (x *ActivationRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationRecordRequest.ProtoReflect.Descriptor instead.
func (*ActivationRecordRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{15}
}

func (x *ActivationRecordRequest) GetUnbrick() bool {
	if x != nil {
		return x.Unbrick
	}
	return false
}

func (x *ActivationRecordRequest) GetAccountTokenCertificate() []byte {
	if x != nil {
		return x.AccountTokenCertificate
	}
	return nil
}

func (x *ActivationRecordRequest) GetDeviceCertificate() []byte {
	if x != nil {
		return x.DeviceCertificate
	}
	return nil
}

func (x *ActivationRecordRequest) GetRegulatoryInfo() []byte {
	if x != nil {
		return x.RegulatoryInfo
	}
	return nil
}

func (x *ActivationRecordRequest) GetFairplayKeyData() []byte {
	if x != nil {
		return x.FairplayKeyData
	}
	return nil
}

func (x *ActivationRecordRequest) GetAccountToken() []byte {
	if x != nil {
		return x.AccountToken
	}
	return nil
}

func (x *ActivationRecordRequest) GetAccountTokenSignature() []byte {
	if x != nil {
		return x.AccountTokenSignature
	}
	return nil
}

func (x *ActivationRecordRequest) GetUniqueDeviceCertificate() []byte {
	if x != nil {
		return x.UniqueDeviceCertificate
	}
	return nil
}

// 激活记录响应
type ActivationRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PscSui        []byte                 `protobuf:"bytes,1,opt,name=psc_sui,json=pscSui,proto3" json:"psc_sui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivationRecordResponse) Reset() {
	*x = ActivationRecordResponse{}
	mi := &file_crypto_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationRecordResponse) ProtoMessage() {}

func (x *ActivationRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationRecordResponse.ProtoReflect.Descriptor instead.
func (*ActivationRecordResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{16}
}

func (x *ActivationRecordResponse) GetPscSui() []byte {
	if x != nil {
		return x.PscSui
	}
	return nil
}

// ADI 开始配置请求
type ADIStartProvisioningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DSID          int64                  `protobuf:"varint,1,opt,name=DSID,proto3" json:"DSID,omitempty"`
	SPIM          []byte                 `protobuf:"bytes,2,opt,name=SPIM,proto3" json:"SPIM,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADIStartProvisioningRequest) Reset() {
	*x = ADIStartProvisioningRequest{}
	mi := &file_crypto_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADIStartProvisioningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADIStartProvisioningRequest) ProtoMessage() {}

func (x *ADIStartProvisioningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADIStartProvisioningRequest.ProtoReflect.Descriptor instead.
func (*ADIStartProvisioningRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{17}
}

func (x *ADIStartProvisioningRequest) GetDSID() int64 {
	if x != nil {
		return x.DSID
	}
	return 0
}

func (x *ADIStartProvisioningRequest) GetSPIM() []byte {
	if x != nil {
		return x.SPIM
	}
	return nil
}

// ADI 开始配置响应
type ADIStartProvisioningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       uint64                 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	CPIM          []byte                 `protobuf:"bytes,2,opt,name=CPIM,proto3" json:"CPIM,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADIStartProvisioningResponse) Reset() {
	*x = ADIStartProvisioningResponse{}
	mi := &file_crypto_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADIStartProvisioningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADIStartProvisioningResponse) ProtoMessage() {}

func (x *ADIStartProvisioningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADIStartProvisioningResponse.ProtoReflect.Descriptor instead.
func (*ADIStartProvisioningResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{18}
}

func (x *ADIStartProvisioningResponse) GetSession() uint64 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *ADIStartProvisioningResponse) GetCPIM() []byte {
	if x != nil {
		return x.CPIM
	}
	return nil
}

// ADI 结束配置请求
type ADIEndProvisioningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       uint64                 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	DSID          int64                  `protobuf:"varint,2,opt,name=DSID,proto3" json:"DSID,omitempty"`
	RINFO         int64                  `protobuf:"varint,3,opt,name=RINFO,proto3" json:"RINFO,omitempty"`
	PTM           []byte                 `protobuf:"bytes,4,opt,name=PTM,proto3" json:"PTM,omitempty"`
	TK            []byte                 `protobuf:"bytes,5,opt,name=TK,proto3" json:"TK,omitempty"`
	ADI           []byte                 `protobuf:"bytes,6,opt,name=ADI,proto3" json:"ADI,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADIEndProvisioningRequest) Reset() {
	*x = ADIEndProvisioningRequest{}
	mi := &file_crypto_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADIEndProvisioningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADIEndProvisioningRequest) ProtoMessage() {}

func (x *ADIEndProvisioningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADIEndProvisioningRequest.ProtoReflect.Descriptor instead.
func (*ADIEndProvisioningRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{19}
}

func (x *ADIEndProvisioningRequest) GetSession() uint64 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *ADIEndProvisioningRequest) GetDSID() int64 {
	if x != nil {
		return x.DSID
	}
	return 0
}

func (x *ADIEndProvisioningRequest) GetRINFO() int64 {
	if x != nil {
		return x.RINFO
	}
	return 0
}

func (x *ADIEndProvisioningRequest) GetPTM() []byte {
	if x != nil {
		return x.PTM
	}
	return nil
}

func (x *ADIEndProvisioningRequest) GetTK() []byte {
	if x != nil {
		return x.TK
	}
	return nil
}

func (x *ADIEndProvisioningRequest) GetADI() []byte {
	if x != nil {
		return x.ADI
	}
	return nil
}

// ADI 结束配置响应
type ADIEndProvisioningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MID           []byte                 `protobuf:"bytes,1,opt,name=MID,proto3" json:"MID,omitempty"`
	OTP           []byte                 `protobuf:"bytes,2,opt,name=OTP,proto3" json:"OTP,omitempty"`
	ADI           []byte                 `protobuf:"bytes,3,opt,name=ADI,proto3" json:"ADI,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADIEndProvisioningResponse) Reset() {
	*x = ADIEndProvisioningResponse{}
	mi := &file_crypto_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADIEndProvisioningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADIEndProvisioningResponse) ProtoMessage() {}

func (x *ADIEndProvisioningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADIEndProvisioningResponse.ProtoReflect.Descriptor instead.
func (*ADIEndProvisioningResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{20}
}

func (x *ADIEndProvisioningResponse) GetMID() []byte {
	if x != nil {
		return x.MID
	}
	return nil
}

func (x *ADIEndProvisioningResponse) GetOTP() []byte {
	if x != nil {
		return x.OTP
	}
	return nil
}

func (x *ADIEndProvisioningResponse) GetADI() []byte {
	if x != nil {
		return x.ADI
	}
	return nil
}

// ADI 生成登录码请求
type ADIGenerateLoginCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DSID          int64                  `protobuf:"varint,1,opt,name=DSID,proto3" json:"DSID,omitempty"`
	ADI           []byte                 `protobuf:"bytes,2,opt,name=ADI,proto3" json:"ADI,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADIGenerateLoginCodeRequest) Reset() {
	*x = ADIGenerateLoginCodeRequest{}
	mi := &file_crypto_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADIGenerateLoginCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADIGenerateLoginCodeRequest) ProtoMessage() {}

func (x *ADIGenerateLoginCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADIGenerateLoginCodeRequest.ProtoReflect.Descriptor instead.
func (*ADIGenerateLoginCodeRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{21}
}

func (x *ADIGenerateLoginCodeRequest) GetDSID() int64 {
	if x != nil {
		return x.DSID
	}
	return 0
}

func (x *ADIGenerateLoginCodeRequest) GetADI() []byte {
	if x != nil {
		return x.ADI
	}
	return nil
}

// ADI 生成登录码响应
type ADIGenerateLoginCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	LoginCode     uint32                 `protobuf:"varint,2,opt,name=login_code,json=loginCode,proto3" json:"login_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADIGenerateLoginCodeResponse) Reset() {
	*x = ADIGenerateLoginCodeResponse{}
	mi := &file_crypto_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADIGenerateLoginCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADIGenerateLoginCodeResponse) ProtoMessage() {}

func (x *ADIGenerateLoginCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADIGenerateLoginCodeResponse.ProtoReflect.Descriptor instead.
func (*ADIGenerateLoginCodeResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{22}
}

func (x *ADIGenerateLoginCodeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ADIGenerateLoginCodeResponse) GetLoginCode() uint32 {
	if x != nil {
		return x.LoginCode
	}
	return 0
}

// Absinthe Hello 请求
type AbsintheHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          int32                  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsintheHelloRequest) Reset() {
	*x = AbsintheHelloRequest{}
	mi := &file_crypto_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheHelloRequest) ProtoMessage() {}

func (x *AbsintheHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheHelloRequest.ProtoReflect.Descriptor instead.
func (*AbsintheHelloRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{23}
}

func (x *AbsintheHelloRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// Absinthe Hello 响应
type AbsintheHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HelloMessage  []byte                 `protobuf:"bytes,1,opt,name=hello_message,json=helloMessage,proto3" json:"hello_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsintheHelloResponse) Reset() {
	*x = AbsintheHelloResponse{}
	mi := &file_crypto_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheHelloResponse) ProtoMessage() {}

func (x *AbsintheHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheHelloResponse.ProtoReflect.Descriptor instead.
func (*AbsintheHelloResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{24}
}

func (x *AbsintheHelloResponse) GetHelloMessage() []byte {
	if x != nil {
		return x.HelloMessage
	}
	return nil
}

// Absinthe 添加选项请求
type AbsintheAddOptionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BikKey               []byte                 `protobuf:"bytes,1,opt,name=bik_key,json=bikKey,proto3" json:"bik_key,omitempty"`
	BaaCert              []byte                 `protobuf:"bytes,2,opt,name=baa_cert,json=baaCert,proto3" json:"baa_cert,omitempty"`
	IntermediateRootCert []byte                 `protobuf:"bytes,3,opt,name=intermediate_root_cert,json=intermediateRootCert,proto3" json:"intermediate_root_cert,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AbsintheAddOptionRequest) Reset() {
	*x = AbsintheAddOptionRequest{}
	mi := &file_crypto_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheAddOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheAddOptionRequest) ProtoMessage() {}

func (x *AbsintheAddOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheAddOptionRequest.ProtoReflect.Descriptor instead.
func (*AbsintheAddOptionRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{25}
}

func (x *AbsintheAddOptionRequest) GetBikKey() []byte {
	if x != nil {
		return x.BikKey
	}
	return nil
}

func (x *AbsintheAddOptionRequest) GetBaaCert() []byte {
	if x != nil {
		return x.BaaCert
	}
	return nil
}

func (x *AbsintheAddOptionRequest) GetIntermediateRootCert() []byte {
	if x != nil {
		return x.IntermediateRootCert
	}
	return nil
}

// Absinthe 添加选项响应
type AbsintheAddOptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsintheAddOptionResponse) Reset() {
	*x = AbsintheAddOptionResponse{}
	mi := &file_crypto_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheAddOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheAddOptionResponse) ProtoMessage() {}

func (x *AbsintheAddOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheAddOptionResponse.ProtoReflect.Descriptor instead.
func (*AbsintheAddOptionResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{26}
}

// Absinthe 激活会话请求
type AbsintheActivateSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ValidationData []byte                 `protobuf:"bytes,1,opt,name=validation_data,json=validationData,proto3" json:"validation_data,omitempty"`
	ServerKey      []byte                 `protobuf:"bytes,2,opt,name=server_key,json=serverKey,proto3" json:"server_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AbsintheActivateSessionRequest) Reset() {
	*x = AbsintheActivateSessionRequest{}
	mi := &file_crypto_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheActivateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheActivateSessionRequest) ProtoMessage() {}

func (x *AbsintheActivateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheActivateSessionRequest.ProtoReflect.Descriptor instead.
func (*AbsintheActivateSessionRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{27}
}

func (x *AbsintheActivateSessionRequest) GetValidationData() []byte {
	if x != nil {
		return x.ValidationData
	}
	return nil
}

func (x *AbsintheActivateSessionRequest) GetServerKey() []byte {
	if x != nil {
		return x.ServerKey
	}
	return nil
}

// Absinthe 激活会话响应
type AbsintheActivateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsintheActivateSessionResponse) Reset() {
	*x = AbsintheActivateSessionResponse{}
	mi := &file_crypto_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheActivateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheActivateSessionResponse) ProtoMessage() {}

func (x *AbsintheActivateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheActivateSessionResponse.ProtoReflect.Descriptor instead.
func (*AbsintheActivateSessionResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{28}
}

// Absinthe 签名数据请求
type AbsintheSignDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignData      []byte                 `protobuf:"bytes,1,opt,name=sign_data,json=signData,proto3" json:"sign_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsintheSignDataRequest) Reset() {
	*x = AbsintheSignDataRequest{}
	mi := &file_crypto_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheSignDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheSignDataRequest) ProtoMessage() {}

func (x *AbsintheSignDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheSignDataRequest.ProtoReflect.Descriptor instead.
func (*AbsintheSignDataRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{29}
}

func (x *AbsintheSignDataRequest) GetSignData() []byte {
	if x != nil {
		return x.SignData
	}
	return nil
}

// Absinthe 签名数据响应
type AbsintheSignDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	OutServKey    []byte                 `protobuf:"bytes,2,opt,name=out_serv_key,json=outServKey,proto3" json:"out_serv_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsintheSignDataResponse) Reset() {
	*x = AbsintheSignDataResponse{}
	mi := &file_crypto_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheSignDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheSignDataResponse) ProtoMessage() {}

func (x *AbsintheSignDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheSignDataResponse.ProtoReflect.Descriptor instead.
func (*AbsintheSignDataResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{30}
}

func (x *AbsintheSignDataResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AbsintheSignDataResponse) GetOutServKey() []byte {
	if x != nil {
		return x.OutServKey
	}
	return nil
}

// Identity 会话请求
type IdentitySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cert          []byte                 `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentitySessionRequest) Reset() {
	*x = IdentitySessionRequest{}
	mi := &file_crypto_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySessionRequest) ProtoMessage() {}

func (x *IdentitySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySessionRequest.ProtoReflect.Descriptor instead.
func (*IdentitySessionRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{31}
}

func (x *IdentitySessionRequest) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

// Identity 会话响应
type IdentitySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       []byte                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentitySessionResponse) Reset() {
	*x = IdentitySessionResponse{}
	mi := &file_crypto_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySessionResponse) ProtoMessage() {}

func (x *IdentitySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySessionResponse.ProtoReflect.Descriptor instead.
func (*IdentitySessionResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{32}
}

func (x *IdentitySessionResponse) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

// Identity 验证请求
type IdentityValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      []byte                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	SignData      []byte                 `protobuf:"bytes,2,opt,name=sign_data,json=signData,proto3" json:"sign_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityValidationRequest) Reset() {
	*x = IdentityValidationRequest{}
	mi := &file_crypto_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityValidationRequest) ProtoMessage() {}

func (x *IdentityValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityValidationRequest.ProtoReflect.Descriptor instead.
func (*IdentityValidationRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{33}
}

func (x *IdentityValidationRequest) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *IdentityValidationRequest) GetSignData() []byte {
	if x != nil {
		return x.SignData
	}
	return nil
}

// Identity 验证响应
type IdentityValidationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ValidationData []byte                 `protobuf:"bytes,1,opt,name=validation_data,json=validationData,proto3" json:"validation_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IdentityValidationResponse) Reset() {
	*x = IdentityValidationResponse{}
	mi := &file_crypto_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityValidationResponse) ProtoMessage() {}

func (x *IdentityValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityValidationResponse.ProtoReflect.Descriptor instead.
func (*IdentityValidationResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{34}
}

func (x *IdentityValidationResponse) GetValidationData() []byte {
	if x != nil {
		return x.ValidationData
	}
	return nil
}

// SAP 交换请求
type SAPExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPExchangeRequest) Reset() {
	*x = SAPExchangeRequest{}
	mi := &file_crypto_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPExchangeRequest) ProtoMessage() {}

func (x *SAPExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPExchangeRequest.ProtoReflect.Descriptor instead.
func (*SAPExchangeRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{35}
}

func (x *SAPExchangeRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SAPExchangeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// SAP 交换响应
type SAPExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeData  []byte                 `protobuf:"bytes,1,opt,name=exchange_data,json=exchangeData,proto3" json:"exchange_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPExchangeResponse) Reset() {
	*x = SAPExchangeResponse{}
	mi := &file_crypto_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPExchangeResponse) ProtoMessage() {}

func (x *SAPExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPExchangeResponse.ProtoReflect.Descriptor instead.
func (*SAPExchangeResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{36}
}

func (x *SAPExchangeResponse) GetExchangeData() []byte {
	if x != nil {
		return x.ExchangeData
	}
	return nil
}

// SAP 质数签名请求
type SAPSignPrimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignData      []byte                 `protobuf:"bytes,1,opt,name=sign_data,json=signData,proto3" json:"sign_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPSignPrimeRequest) Reset() {
	*x = SAPSignPrimeRequest{}
	mi := &file_crypto_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPSignPrimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPSignPrimeRequest) ProtoMessage() {}

func (x *SAPSignPrimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPSignPrimeRequest.ProtoReflect.Descriptor instead.
func (*SAPSignPrimeRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{37}
}

func (x *SAPSignPrimeRequest) GetSignData() []byte {
	if x != nil {
		return x.SignData
	}
	return nil
}

// SAP 质数签名响应
type SAPSignPrimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPSignPrimeResponse) Reset() {
	*x = SAPSignPrimeResponse{}
	mi := &file_crypto_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPSignPrimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPSignPrimeResponse) ProtoMessage() {}

func (x *SAPSignPrimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPSignPrimeResponse.ProtoReflect.Descriptor instead.
func (*SAPSignPrimeResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{38}
}

func (x *SAPSignPrimeResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// SAP 质数验证请求
type SAPVerifyPrimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPVerifyPrimeRequest) Reset() {
	*x = SAPVerifyPrimeRequest{}
	mi := &file_crypto_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPVerifyPrimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPVerifyPrimeRequest) ProtoMessage() {}

func (x *SAPVerifyPrimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPVerifyPrimeRequest.ProtoReflect.Descriptor instead.
func (*SAPVerifyPrimeRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{39}
}

func (x *SAPVerifyPrimeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// SAP 质数验证响应
type SAPVerifyPrimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPVerifyPrimeResponse) Reset() {
	*x = SAPVerifyPrimeResponse{}
	mi := &file_crypto_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPVerifyPrimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPVerifyPrimeResponse) ProtoMessage() {}

func (x *SAPVerifyPrimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPVerifyPrimeResponse.ProtoReflect.Descriptor instead.
func (*SAPVerifyPrimeResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{40}
}

// SAP 签名请求
type SAPSignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignData      []byte                 `protobuf:"bytes,1,opt,name=sign_data,json=signData,proto3" json:"sign_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPSignRequest) Reset() {
	*x = SAPSignRequest{}
	mi := &file_crypto_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPSignRequest) ProtoMessage() {}

func (x *SAPSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPSignRequest.ProtoReflect.Descriptor instead.
func (*SAPSignRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{41}
}

func (x *SAPSignRequest) GetSignData() []byte {
	if x != nil {
		return x.SignData
	}
	return nil
}

// SAP 签名响应
type SAPSignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPSignResponse) Reset() {
	*x = SAPSignResponse{}
	mi := &file_crypto_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPSignResponse) ProtoMessage() {}

func (x *SAPSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPSignResponse.ProtoReflect.Descriptor instead.
func (*SAPSignResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{42}
}

func (x *SAPSignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// SAP 验证请求
type SAPVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPVerifyRequest) Reset() {
	*x = SAPVerifyRequest{}
	mi := &file_crypto_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPVerifyRequest) ProtoMessage() {}

func (x *SAPVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPVerifyRequest.ProtoReflect.Descriptor instead.
func (*SAPVerifyRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{43}
}

func (x *SAPVerifyRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SAPVerifyRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// SAP 验证响应
type SAPVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPVerifyResponse) Reset() {
	*x = SAPVerifyResponse{}
	mi := &file_crypto_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPVerifyResponse) ProtoMessage() {}

func (x *SAPVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPVerifyResponse.ProtoReflect.Descriptor instead.
func (*SAPVerifyResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{44}
}

var File_crypto_proto protoreflect.FileDescriptor

const file_crypto_proto_rawDesc = "" +
	"\n" +
	"\fcrypto.proto\x12\aicrypto\x1a\x1cgoogle/api/annotations.proto\"\x9c\x01\n" +
	"\x11InitializeRequest\x12\x16\n" +
	"\x06device\x18\x02 \x01(\fR\x06device\x12\x17\n" +
	"\aios_drm\x18\x04 \x01(\bR\x06iosDrm\x12:\n" +
	"\rmacos_runtime\x18\x05 \x01(\x0e2\x15.icrypto.MacOSRuntimeR\fmacosRuntimeJ\x04\b\x01\x10\x02J\x04\b\x03\x10\x04R\x04typeR\bcontrols\",\n" +
	"\x12InitializeResponse\x12\x16\n" +
	"\x06device\x18\x01 \x01(\fR\x06device\"+\n" +
	"\x11SyncDeviceRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\fR\x06device\"\x14\n" +
	"\x12SyncDeviceResponse\"!\n" +
	"\x0fFinalizeRequestJ\x04\b\x01\x10\x02R\bcontrols\"\x12\n" +
	"\x10FinalizeResponse\"/\n" +
	"\x1dActivationDRMHandshakeRequestJ\x04\b\x01\x10\x02R\bcontrols\"\x85\x01\n" +
	"\x1eActivationDRMHandshakeResponse\x12'\n" +
	"\x0fcollection_blob\x18\x01 \x01(\fR\x0ecollectionBlob\x12:\n" +
	"\x19handshake_request_message\x18\x02 \x01(\fR\x17handshakeRequestMessage\"\x9f\x01\n" +
	"\x1bActivationDRMProcessRequest\x12\x16\n" +
	"\x06SUInfo\x18\x01 \x01(\fR\x06SUInfo\x12<\n" +
	"\x1ahandshake_response_message\x18\x02 \x01(\fR\x18handshakeResponseMessage\x12\x1a\n" +
	"\bserverKP\x18\x03 \x01(\fR\bserverKPJ\x04\b\x04\x10\x05R\bcontrols\"@\n" +
	"\x1cActivationDRMProcessResponse\x12\x10\n" +
	"\x03UIK\x18\x01 \x01(\fR\x03UIK\x12\x0e\n" +
	"\x02RK\x18\x02 \x01(\fR\x02RK\"_\n" +
	"\x1dActivationDRMSignatureRequest\x12.\n" +
	"\x13activation_info_xml\x18\x01 \x01(\fR\x11activationInfoXmlJ\x04\b\x02\x10\x03R\bcontrols\"\xe7\x01\n" +
	"\x1eActivationDRMSignatureResponse\x12.\n" +
	"\x13fairplay_cert_chain\x18\x01 \x01(\fR\x11fairplayCertChain\x12-\n" +
	"\x12fairplay_signature\x18\x02 \x01(\fR\x11fairplaySignature\x12 \n" +
	"\vRKSignature\x18\x03 \x01(\fR\vRKSignature\x12(\n" +
	"\x10sign_act_request\x18\x04 \x01(\fR\x0esignActRequest\x12\x1a\n" +
	"\bserverKP\x18\x05 \x01(\fR\bserverKP\"\xe4\x01\n" +
	"\x15ActivationSignRequest\x12;\n" +
	"\aprofile\x18\x01 \x01(\x0e2!.icrypto.ActivationSigningProfileR\aprofile\x12:\n" +
	"\rmacos_runtime\x18\x05 \x01(\x0e2\x15.icrypto.MacOSRuntimeR\fmacosRuntime\x12\x16\n" +
	"\x06device\x18\x03 \x01(\fR\x06device\x12.\n" +
	"\x13activation_info_xml\x18\x04 \x01(\fR\x11activationInfoXmlJ\x04\b\x02\x10\x03R\x04type\"]\n" +
	"\x1bActivationDeprecatedRequest\x12.\n" +
	"\x13activation_info_xml\x18\x01 \x01(\fR\x11activationInfoXmlJ\x04\b\x02\x10\x03R\bcontrols\"F\n" +
	"\x1cActivationDeprecatedResponse\x12\x12\n" +
	"\x04sign\x18\x01 \x01(\fR\x04sign\x12\x12\n" +
	"\x04cert\x18\x02 \x01(\fR\x04cert\"\x9c\x03\n" +
	"\x17ActivationRecordRequest\x12\x18\n" +
	"\aunbrick\x18\x01 \x01(\bR\aunbrick\x12:\n" +
	"\x19account_token_certificate\x18\x02 \x01(\fR\x17accountTokenCertificate\x12-\n" +
	"\x12device_certificate\x18\x03 \x01(\fR\x11deviceCertificate\x12'\n" +
	"\x0fregulatory_info\x18\x04 \x01(\fR\x0eregulatoryInfo\x12*\n" +
	"\x11fairplay_key_data\x18\x05 \x01(\fR\x0ffairplayKeyData\x12#\n" +
	"\raccount_token\x18\x06 \x01(\fR\faccountToken\x126\n" +
	"\x17account_token_signature\x18\a \x01(\fR\x15accountTokenSignature\x12:\n" +
	"\x19unique_device_certificate\x18\b \x01(\fR\x17uniqueDeviceCertificateJ\x04\b\t\x10\n" +
	"R\bcontrols\"3\n" +
	"\x18ActivationRecordResponse\x12\x17\n" +
	"\apsc_sui\x18\x01 \x01(\fR\x06pscSui\"U\n" +
	"\x1bADIStartProvisioningRequest\x12\x12\n" +
	"\x04DSID\x18\x01 \x01(\x03R\x04DSID\x12\x12\n" +
	"\x04SPIM\x18\x02 \x01(\fR\x04SPIMJ\x04\b\x03\x10\x04R\bcontrols\"L\n" +
	"\x1cADIStartProvisioningResponse\x12\x18\n" +
	"\asession\x18\x01 \x01(\x04R\asession\x12\x12\n" +
	"\x04CPIM\x18\x02 \x01(\fR\x04CPIM\"\xa3\x01\n" +
	"\x19ADIEndProvisioningRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\x04R\asession\x12\x12\n" +
	"\x04DSID\x18\x02 \x01(\x03R\x04DSID\x12\x14\n" +
	"\x05RINFO\x18\x03 \x01(\x03R\x05RINFO\x12\x10\n" +
	"\x03PTM\x18\x04 \x01(\fR\x03PTM\x12\x0e\n" +
	"\x02TK\x18\x05 \x01(\fR\x02TK\x12\x10\n" +
	"\x03ADI\x18\x06 \x01(\fR\x03ADIJ\x04\b\a\x10\bR\bcontrols\"R\n" +
	"\x1aADIEndProvisioningResponse\x12\x10\n" +
	"\x03MID\x18\x01 \x01(\fR\x03MID\x12\x10\n" +
	"\x03OTP\x18\x02 \x01(\fR\x03OTP\x12\x10\n" +
	"\x03ADI\x18\x03 \x01(\fR\x03ADI\"S\n" +
	"\x1bADIGenerateLoginCodeRequest\x12\x12\n" +
	"\x04DSID\x18\x01 \x01(\x03R\x04DSID\x12\x10\n" +
	"\x03ADI\x18\x02 \x01(\fR\x03ADIJ\x04\b\x03\x10\x04R\bcontrols\"Q\n" +
	"\x1cADIGenerateLoginCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1d\n" +
	"\n" +
	"login_code\x18\x02 \x01(\rR\tloginCode\":\n" +
	"\x14AbsintheHelloRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\x05R\x04modeJ\x04\b\x02\x10\x03R\bcontrols\"<\n" +
	"\x15AbsintheHelloResponse\x12#\n" +
	"\rhello_message\x18\x01 \x01(\fR\fhelloMessage\"\x94\x01\n" +
	"\x18AbsintheAddOptionRequest\x12\x17\n" +
	"\abik_key\x18\x01 \x01(\fR\x06bikKey\x12\x19\n" +
	"\bbaa_cert\x18\x02 \x01(\fR\abaaCert\x124\n" +
	"\x16intermediate_root_cert\x18\x03 \x01(\fR\x14intermediateRootCertJ\x04\b\x04\x10\x05R\bcontrols\"\x1b\n" +
	"\x19AbsintheAddOptionResponse\"x\n" +
	"\x1eAbsintheActivateSessionRequest\x12'\n" +
	"\x0fvalidation_data\x18\x01 \x01(\fR\x0evalidationData\x12\x1d\n" +
	"\n" +
	"server_key\x18\x02 \x01(\fR\tserverKeyJ\x04\b\x03\x10\x04R\bcontrols\"!\n" +
	"\x1fAbsintheActivateSessionResponse\"F\n" +
	"\x17AbsintheSignDataRequest\x12\x1b\n" +
	"\tsign_data\x18\x01 \x01(\fR\bsignDataJ\x04\b\x02\x10\x03R\bcontrols\"Z\n" +
	"\x18AbsintheSignDataResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12 \n" +
	"\fout_serv_key\x18\x02 \x01(\fR\n" +
	"outServKey\"<\n" +
	"\x16IdentitySessionRequest\x12\x12\n" +
	"\x04cert\x18\x01 \x01(\fR\x04certJ\x04\b\x02\x10\x03R\bcontrols\"3\n" +
	"\x17IdentitySessionResponse\x12\x18\n" +
	"\arequest\x18\x01 \x01(\fR\arequest\"d\n" +
	"\x19IdentityValidationRequest\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\x12\x1b\n" +
	"\tsign_data\x18\x02 \x01(\fR\bsignDataJ\x04\b\x03\x10\x04R\bcontrols\"E\n" +
	"\x1aIdentityValidationResponse\x12'\n" +
	"\x0fvalidation_data\x18\x01 \x01(\fR\x0evalidationData\"R\n" +
	"\x12SAPExchangeRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04dataJ\x04\b\x03\x10\x04R\bcontrols\":\n" +
	"\x13SAPExchangeResponse\x12#\n" +
	"\rexchange_data\x18\x01 \x01(\fR\fexchangeData\"B\n" +
	"\x13SAPSignPrimeRequest\x12\x1b\n" +
	"\tsign_data\x18\x01 \x01(\fR\bsignDataJ\x04\b\x02\x10\x03R\bcontrols\"4\n" +
	"\x14SAPSignPrimeResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\";\n" +
	"\x15SAPVerifyPrimeRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataJ\x04\b\x02\x10\x03R\bcontrols\"\x18\n" +
	"\x16SAPVerifyPrimeResponse\"=\n" +
	"\x0eSAPSignRequest\x12\x1b\n" +
	"\tsign_data\x18\x01 \x01(\fR\bsignDataJ\x04\b\x02\x10\x03R\bcontrols\"/\n" +
	"\x0fSAPSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"T\n" +
	"\x10SAPVerifyRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignatureJ\x04\b\x03\x10\x04R\bcontrols\"\x13\n" +
	"\x11SAPVerifyResponse*4\n" +
	"\fMacOSRuntime\x12\x0e\n" +
	"\n" +
	"MACOS_AUTO\x10\x00\x12\x14\n" +
	"\x10MACOS_COMPATIBLE\x10\x01*^\n" +
	"\x18ActivationSigningProfile\x12\x1e\n" +
	"\x1aACTIVATION_SIGNING_CURRENT\x10\x00\x12\"\n" +
	"\x1eACTIVATION_SIGNING_LEGACY_IOS9\x10\x012\xb9\x15\n" +
	"\fCryptService\x12t\n" +
	"\x0eActivationSign\x12\x1e.icrypto.ActivationSignRequest\x1a%.icrypto.ActivationDeprecatedResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/activation/sign\x12]\n" +
	"\n" +
	"Initialize\x12\x1a.icrypto.InitializeRequest\x1a\x1b.icrypto.InitializeResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/initialize\x12^\n" +
	"\n" +
	"SyncDevice\x12\x1a.icrypto.SyncDeviceRequest\x1a\x1b.icrypto.SyncDeviceResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/device/sync\x12U\n" +
	"\bFinalize\x12\x18.icrypto.FinalizeRequest\x1a\x19.icrypto.FinalizeResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/finalize\x12\x8f\x01\n" +
	"\x16ActivationDRMHandshake\x12&.icrypto.ActivationDRMHandshakeRequest\x1a'.icrypto.ActivationDRMHandshakeResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/activation/drm/handshake\x12\x87\x01\n" +
	"\x14ActivationDRMProcess\x12$.icrypto.ActivationDRMProcessRequest\x1a%.icrypto.ActivationDRMProcessResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/activation/drm/process\x12\x8f\x01\n" +
	"\x16ActivationDRMSignature\x12&.icrypto.ActivationDRMSignatureRequest\x1a'.icrypto.ActivationDRMSignatureResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/activation/drm/signature\x12\x86\x01\n" +
	"\x14ActivationDeprecated\x12$.icrypto.ActivationDeprecatedRequest\x1a%.icrypto.ActivationDeprecatedResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/activation/deprecated\x12v\n" +
	"\x10ActivationRecord\x12 .icrypto.ActivationRecordRequest\x1a!.icrypto.ActivationRecordResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/activation/record\x12\x87\x01\n" +
	"\x14ADIStartProvisioning\x12$.icrypto.ADIStartProvisioningRequest\x1a%.icrypto.ADIStartProvisioningResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/adi/start-provisioning\x12\x7f\n" +
	"\x12ADIEndProvisioning\x12\".icrypto.ADIEndProvisioningRequest\x1a#.icrypto.ADIEndProvisioningResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/adi/end-provisioning\x12\x88\x01\n" +
	"\x14ADIGenerateLoginCode\x12$.icrypto.ADIGenerateLoginCodeRequest\x1a%.icrypto.ADIGenerateLoginCodeResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/adi/generate-login-code\x12j\n" +
	"\rAbsintheHello\x12\x1d.icrypto.AbsintheHelloRequest\x1a\x1e.icrypto.AbsintheHelloResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/absinthe/hello\x12{\n" +
	"\x11AbsintheAddOption\x12!.icrypto.AbsintheAddOptionRequest\x1a\".icrypto.AbsintheAddOptionResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/absinthe/add-option\x12\x93\x01\n" +
	"\x17AbsintheActivateSession\x12'.icrypto.AbsintheActivateSessionRequest\x1a(.icrypto.AbsintheActivateSessionResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/absinthe/activate-session\x12w\n" +
	"\x10AbsintheSignData\x12 .icrypto.AbsintheSignDataRequest\x1a!.icrypto.AbsintheSignDataResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/absinthe/sign-data\x12r\n" +
	"\x0fIdentitySession\x12\x1f.icrypto.IdentitySessionRequest\x1a .icrypto.IdentitySessionResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/identity/session\x12~\n" +
	"\x12IdentityValidation\x12\".icrypto.IdentityValidationRequest\x1a#.icrypto.IdentityValidationResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/identity/validation\x12b\n" +
	"\vSAPExchange\x12\x1b.icrypto.SAPExchangeRequest\x1a\x1c.icrypto.SAPExchangeResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/sap/exchange\x12g\n" +
	"\fSAPSignPrime\x12\x1c.icrypto.SAPSignPrimeRequest\x1a\x1d.icrypto.SAPSignPrimeResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/sap/sign-prime\x12o\n" +
	"\x0eSAPVerifyPrime\x12\x1e.icrypto.SAPVerifyPrimeRequest\x1a\x1f.icrypto.SAPVerifyPrimeResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/sap/verify-prime\x12R\n" +
	"\aSAPSign\x12\x17.icrypto.SAPSignRequest\x1a\x18.icrypto.SAPSignResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/sap/sign\x12Z\n" +
	"\tSAPVerify\x12\x19.icrypto.SAPVerifyRequest\x1a\x1a.icrypto.SAPVerifyResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/sap/verifyB\x1eZ\x1cgithub.com/zdypro888/icryptob\x06proto3"

var (
	file_crypto_proto_rawDescOnce sync.Once
	file_crypto_proto_rawDescData []byte
)

func file_crypto_proto_rawDescGZIP() []byte {
	file_crypto_proto_rawDescOnce.Do(func() {
		file_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crypto_proto_rawDesc), len(file_crypto_proto_rawDesc)))
	})
	return file_crypto_proto_rawDescData
}

var file_crypto_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_crypto_proto_goTypes = []any{
	(MacOSRuntime)(0),                       // 0: icrypto.MacOSRuntime
	(ActivationSigningProfile)(0),           // 1: icrypto.ActivationSigningProfile
	(*InitializeRequest)(nil),               // 2: icrypto.InitializeRequest
	(*InitializeResponse)(nil),              // 3: icrypto.InitializeResponse
	(*SyncDeviceRequest)(nil),               // 4: icrypto.SyncDeviceRequest
	(*SyncDeviceResponse)(nil),              // 5: icrypto.SyncDeviceResponse
	(*FinalizeRequest)(nil),                 // 6: icrypto.FinalizeRequest
	(*FinalizeResponse)(nil),                // 7: icrypto.FinalizeResponse
	(*ActivationDRMHandshakeRequest)(nil),   // 8: icrypto.ActivationDRMHandshakeRequest
	(*ActivationDRMHandshakeResponse)(nil),  // 9: icrypto.ActivationDRMHandshakeResponse
	(*ActivationDRMProcessRequest)(nil),     // 10: icrypto.ActivationDRMProcessRequest
	(*ActivationDRMProcessResponse)(nil),    // 11: icrypto.ActivationDRMProcessResponse
	(*ActivationDRMSignatureRequest)(nil),   // 12: icrypto.ActivationDRMSignatureRequest
	(*ActivationDRMSignatureResponse)(nil),  // 13: icrypto.ActivationDRMSignatureResponse
	(*ActivationSignRequest)(nil),           // 14: icrypto.ActivationSignRequest
	(*ActivationDeprecatedRequest)(nil),     // 15: icrypto.ActivationDeprecatedRequest
	(*ActivationDeprecatedResponse)(nil),    // 16: icrypto.ActivationDeprecatedResponse
	(*ActivationRecordRequest)(nil),         // 17: icrypto.ActivationRecordRequest
	(*ActivationRecordResponse)(nil),        // 18: icrypto.ActivationRecordResponse
	(*ADIStartProvisioningRequest)(nil),     // 19: icrypto.ADIStartProvisioningRequest
	(*ADIStartProvisioningResponse)(nil),    // 20: icrypto.ADIStartProvisioningResponse
	(*ADIEndProvisioningRequest)(nil),       // 21: icrypto.ADIEndProvisioningRequest
	(*ADIEndProvisioningResponse)(nil),      // 22: icrypto.ADIEndProvisioningResponse
	(*ADIGenerateLoginCodeRequest)(nil),     // 23: icrypto.ADIGenerateLoginCodeRequest
	(*ADIGenerateLoginCodeResponse)(nil),    // 24: icrypto.ADIGenerateLoginCodeResponse
	(*AbsintheHelloRequest)(nil),            // 25: icrypto.AbsintheHelloRequest
	(*AbsintheHelloResponse)(nil),           // 26: icrypto.AbsintheHelloResponse
	(*AbsintheAddOptionRequest)(nil),        // 27: icrypto.AbsintheAddOptionRequest
	(*AbsintheAddOptionResponse)(nil),       // 28: icrypto.AbsintheAddOptionResponse
	(*AbsintheActivateSessionRequest)(nil),  // 29: icrypto.AbsintheActivateSessionRequest
	(*AbsintheActivateSessionResponse)(nil), // 30: icrypto.AbsintheActivateSessionResponse
	(*AbsintheSignDataRequest)(nil),         // 31: icrypto.AbsintheSignDataRequest
	(*AbsintheSignDataResponse)(nil),        // 32: icrypto.AbsintheSignDataResponse
	(*IdentitySessionRequest)(nil),          // 33: icrypto.IdentitySessionRequest
	(*IdentitySessionResponse)(nil),         // 34: icrypto.IdentitySessionResponse
	(*IdentityValidationRequest)(nil),       // 35: icrypto.IdentityValidationRequest
	(*IdentityValidationResponse)(nil),      // 36: icrypto.IdentityValidationResponse
	(*SAPExchangeRequest)(nil),              // 37: icrypto.SAPExchangeRequest
	(*SAPExchangeResponse)(nil),             // 38: icrypto.SAPExchangeResponse
	(*SAPSignPrimeRequest)(nil),             // 39: icrypto.SAPSignPrimeRequest
	(*SAPSignPrimeResponse)(nil),            // 40: icrypto.SAPSignPrimeResponse
	(*SAPVerifyPrimeRequest)(nil),           // 41: icrypto.SAPVerifyPrimeRequest
	(*SAPVerifyPrimeResponse)(nil),          // 42: icrypto.SAPVerifyPrimeResponse
	(*SAPSignRequest)(nil),                  // 43: icrypto.SAPSignRequest
	(*SAPSignResponse)(nil),                 // 44: icrypto.SAPSignResponse
	(*SAPVerifyRequest)(nil),                // 45: icrypto.SAPVerifyRequest
	(*SAPVerifyResponse)(nil),               // 46: icrypto.SAPVerifyResponse
}
var file_crypto_proto_depIdxs = []int32{
	0,  // 0: icrypto.InitializeRequest.macos_runtime:type_name -> icrypto.MacOSRuntime
	1,  // 1: icrypto.ActivationSignRequest.profile:type_name -> icrypto.ActivationSigningProfile
	0,  // 2: icrypto.ActivationSignRequest.macos_runtime:type_name -> icrypto.MacOSRuntime
	14, // 3: icrypto.CryptService.ActivationSign:input_type -> icrypto.ActivationSignRequest
	2,  // 4: icrypto.CryptService.Initialize:input_type -> icrypto.InitializeRequest
	4,  // 5: icrypto.CryptService.SyncDevice:input_type -> icrypto.SyncDeviceRequest
	6,  // 6: icrypto.CryptService.Finalize:input_type -> icrypto.FinalizeRequest
	8,  // 7: icrypto.CryptService.ActivationDRMHandshake:input_type -> icrypto.ActivationDRMHandshakeRequest
	10, // 8: icrypto.CryptService.ActivationDRMProcess:input_type -> icrypto.ActivationDRMProcessRequest
	12, // 9: icrypto.CryptService.ActivationDRMSignature:input_type -> icrypto.ActivationDRMSignatureRequest
	15, // 10: icrypto.CryptService.ActivationDeprecated:input_type -> icrypto.ActivationDeprecatedRequest
	17, // 11: icrypto.CryptService.ActivationRecord:input_type -> icrypto.ActivationRecordRequest
	19, // 12: icrypto.CryptService.ADIStartProvisioning:input_type -> icrypto.ADIStartProvisioningRequest
	21, // 13: icrypto.CryptService.ADIEndProvisioning:input_type -> icrypto.ADIEndProvisioningRequest
	23, // 14: icrypto.CryptService.ADIGenerateLoginCode:input_type -> icrypto.ADIGenerateLoginCodeRequest
	25, // 15: icrypto.CryptService.AbsintheHello:input_type -> icrypto.AbsintheHelloRequest
	27, // 16: icrypto.CryptService.AbsintheAddOption:input_type -> icrypto.AbsintheAddOptionRequest
	29, // 17: icrypto.CryptService.AbsintheActivateSession:input_type -> icrypto.AbsintheActivateSessionRequest
	31, // 18: icrypto.CryptService.AbsintheSignData:input_type -> icrypto.AbsintheSignDataRequest
	33, // 19: icrypto.CryptService.IdentitySession:input_type -> icrypto.IdentitySessionRequest
	35, // 20: icrypto.CryptService.IdentityValidation:input_type -> icrypto.IdentityValidationRequest
	37, // 21: icrypto.CryptService.SAPExchange:input_type -> icrypto.SAPExchangeRequest
	39, // 22: icrypto.CryptService.SAPSignPrime:input_type -> icrypto.SAPSignPrimeRequest
	41, // 23: icrypto.CryptService.SAPVerifyPrime:input_type -> icrypto.SAPVerifyPrimeRequest
	43, // 24: icrypto.CryptService.SAPSign:input_type -> icrypto.SAPSignRequest
	45, // 25: icrypto.CryptService.SAPVerify:input_type -> icrypto.SAPVerifyRequest
	16, // 26: icrypto.CryptService.ActivationSign:output_type -> icrypto.ActivationDeprecatedResponse
	3,  // 27: icrypto.CryptService.Initialize:output_type -> icrypto.InitializeResponse
	5,  // 28: icrypto.CryptService.SyncDevice:output_type -> icrypto.SyncDeviceResponse
	7,  // 29: icrypto.CryptService.Finalize:output_type -> icrypto.FinalizeResponse
	9,  // 30: icrypto.CryptService.ActivationDRMHandshake:output_type -> icrypto.ActivationDRMHandshakeResponse
	11, // 31: icrypto.CryptService.ActivationDRMProcess:output_type -> icrypto.ActivationDRMProcessResponse
	13, // 32: icrypto.CryptService.ActivationDRMSignature:output_type -> icrypto.ActivationDRMSignatureResponse
	16, // 33: icrypto.CryptService.ActivationDeprecated:output_type -> icrypto.ActivationDeprecatedResponse
	18, // 34: icrypto.CryptService.ActivationRecord:output_type -> icrypto.ActivationRecordResponse
	20, // 35: icrypto.CryptService.ADIStartProvisioning:output_type -> icrypto.ADIStartProvisioningResponse
	22, // 36: icrypto.CryptService.ADIEndProvisioning:output_type -> icrypto.ADIEndProvisioningResponse
	24, // 37: icrypto.CryptService.ADIGenerateLoginCode:output_type -> icrypto.ADIGenerateLoginCodeResponse
	26, // 38: icrypto.CryptService.AbsintheHello:output_type -> icrypto.AbsintheHelloResponse
	28, // 39: icrypto.CryptService.AbsintheAddOption:output_type -> icrypto.AbsintheAddOptionResponse
	30, // 40: icrypto.CryptService.AbsintheActivateSession:output_type -> icrypto.AbsintheActivateSessionResponse
	32, // 41: icrypto.CryptService.AbsintheSignData:output_type -> icrypto.AbsintheSignDataResponse
	34, // 42: icrypto.CryptService.IdentitySession:output_type -> icrypto.IdentitySessionResponse
	36, // 43: icrypto.CryptService.IdentityValidation:output_type -> icrypto.IdentityValidationResponse
	38, // 44: icrypto.CryptService.SAPExchange:output_type -> icrypto.SAPExchangeResponse
	40, // 45: icrypto.CryptService.SAPSignPrime:output_type -> icrypto.SAPSignPrimeResponse
	42, // 46: icrypto.CryptService.SAPVerifyPrime:output_type -> icrypto.SAPVerifyPrimeResponse
	44, // 47: icrypto.CryptService.SAPSign:output_type -> icrypto.SAPSignResponse
	46, // 48: icrypto.CryptService.SAPVerify:output_type -> icrypto.SAPVerifyResponse
	26, // [26:49] is the sub-list for method output_type
	3,  // [3:26] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_crypto_proto_init() }
func file_crypto_proto_init() {
	if File_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crypto_proto_rawDesc), len(file_crypto_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crypto_proto_goTypes,
		DependencyIndexes: file_crypto_proto_depIdxs,
		EnumInfos:         file_crypto_proto_enumTypes,
		MessageInfos:      file_crypto_proto_msgTypes,
	}.Build()
	File_crypto_proto = out.File
	file_crypto_proto_goTypes = nil
	file_crypto_proto_depIdxs = nil
}
