// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: crypto.proto

package icrypto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 操作系统类型枚举
type OSEnum int32

const (
	OSEnum_UNSPECIFIED OSEnum = 0
	OSEnum_MACOS       OSEnum = 1
	OSEnum_IOS         OSEnum = 2
	OSEnum_ANDROID     OSEnum = 3
)

// Enum value maps for OSEnum.
var (
	OSEnum_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "MACOS",
		2: "IOS",
		3: "ANDROID",
	}
	OSEnum_value = map[string]int32{
		"UNSPECIFIED": 0,
		"MACOS":       1,
		"IOS":         2,
		"ANDROID":     3,
	}
)

func (x OSEnum) Enum() *OSEnum {
	p := new(OSEnum)
	*p = x
	return p
}

func (x OSEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OSEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_crypto_proto_enumTypes[0].Descriptor()
}

func (OSEnum) Type() protoreflect.EnumType {
	return &file_crypto_proto_enumTypes[0]
}

func (x OSEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OSEnum.Descriptor instead.
func (OSEnum) EnumDescriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{0}
}

// 初始化类型枚举
type InitializeType int32

const (
	InitializeType_AUTO           InitializeType = 0
	InitializeType_IOSARCH64      InitializeType = 1
	InitializeType_IOSDRM32       InitializeType = 2
	InitializeType_MACOSDISABLE15 InitializeType = 4
)

// Enum value maps for InitializeType.
var (
	InitializeType_name = map[int32]string{
		0: "AUTO",
		1: "IOSARCH64",
		2: "IOSDRM32",
		4: "MACOSDISABLE15",
	}
	InitializeType_value = map[string]int32{
		"AUTO":           0,
		"IOSARCH64":      1,
		"IOSDRM32":       2,
		"MACOSDISABLE15": 4,
	}
)

func (x InitializeType) Enum() *InitializeType {
	p := new(InitializeType)
	*p = x
	return p
}

func (x InitializeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InitializeType) Descriptor() protoreflect.EnumDescriptor {
	return file_crypto_proto_enumTypes[1].Descriptor()
}

func (InitializeType) Type() protoreflect.EnumType {
	return &file_crypto_proto_enumTypes[1]
}

func (x InitializeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InitializeType.Descriptor instead.
func (InitializeType) EnumDescriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{1}
}

// 设备信息
type Device struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	OsType       OSEnum                 `protobuf:"varint,1,opt,name=os_type,json=osType,proto3,enum=icrypto.OSEnum" json:"os_type,omitempty"`
	SerialNumber string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	// macOS
	Model         string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	OsRevision    uint64 `protobuf:"varint,4,opt,name=os_revision,json=osRevision,proto3" json:"os_revision,omitempty"`
	OsVersion     string `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	BoardId       string `protobuf:"bytes,6,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	DiskId        string `protobuf:"bytes,7,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	HardwareUUID  string `protobuf:"bytes,8,opt,name=hardwareUUID,proto3" json:"hardwareUUID,omitempty"`
	BootUUID      string `protobuf:"bytes,9,opt,name=bootUUID,proto3" json:"bootUUID,omitempty"`
	MACAddress    []byte `protobuf:"bytes,10,opt,name=MACAddress,proto3" json:"MACAddress,omitempty"`
	ROM           []byte `protobuf:"bytes,11,opt,name=ROM,proto3" json:"ROM,omitempty"`
	MLB           string `protobuf:"bytes,12,opt,name=MLB,proto3" json:"MLB,omitempty"`
	KGq3489Ugfi   []byte `protobuf:"bytes,13,opt,name=kGq3489ugfi,proto3" json:"kGq3489ugfi,omitempty"`
	KFyp98Tpgj    []byte `protobuf:"bytes,14,opt,name=kFyp98tpgj,proto3" json:"kFyp98tpgj,omitempty"`
	KkbjfrfpoJU   []byte `protobuf:"bytes,15,opt,name=kkbjfrfpoJU,proto3" json:"kkbjfrfpoJU,omitempty"`
	KoycqAZloTNDm []byte `protobuf:"bytes,16,opt,name=koycqAZloTNDm,proto3" json:"koycqAZloTNDm,omitempty"`
	KabKPld1EcMni []byte `protobuf:"bytes,17,opt,name=kabKPld1EcMni,proto3" json:"kabKPld1EcMni,omitempty"`
	// iOS
	ProductType      string `protobuf:"bytes,18,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	IMEI             string `protobuf:"bytes,19,opt,name=IMEI,proto3" json:"IMEI,omitempty"`
	UniqueChipId     uint64 `protobuf:"varint,20,opt,name=unique_chip_id,json=uniqueChipId,proto3" json:"unique_chip_id,omitempty"`
	UniqueDeviceId   string `protobuf:"bytes,21,opt,name=unique_device_id,json=uniqueDeviceId,proto3" json:"unique_device_id,omitempty"`
	WifiAddress      string `protobuf:"bytes,22,opt,name=wifi_address,json=wifiAddress,proto3" json:"wifi_address,omitempty"`
	BluetoothAddress string `protobuf:"bytes,23,opt,name=bluetooth_address,json=bluetoothAddress,proto3" json:"bluetooth_address,omitempty"`
	SecureElementSN  string `protobuf:"bytes,24,opt,name=secure_elementSN,json=secureElementSN,proto3" json:"secure_elementSN,omitempty"`
	// Global
	BuildVersion    string `protobuf:"bytes,25,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	ProductVersion  string `protobuf:"bytes,26,opt,name=product_version,json=productVersion,proto3" json:"product_version,omitempty"`
	FairplayKeyData []byte `protobuf:"bytes,27,opt,name=fairplay_key_data,json=fairplayKeyData,proto3" json:"fairplay_key_data,omitempty"`
	ADI             []byte `protobuf:"bytes,28,opt,name=ADI,proto3" json:"ADI,omitempty"`
	APTicket        []byte `protobuf:"bytes,29,opt,name=AP_ticket,json=APTicket,proto3" json:"AP_ticket,omitempty"`
	SUInfo          []byte `protobuf:"bytes,30,opt,name=SUInfo,proto3" json:"SUInfo,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetOsType() OSEnum {
	if x != nil {
		return x.OsType
	}
	return OSEnum_UNSPECIFIED
}

func (x *Device) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Device) GetOsRevision() uint64 {
	if x != nil {
		return x.OsRevision
	}
	return 0
}

func (x *Device) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *Device) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *Device) GetDiskId() string {
	if x != nil {
		return x.DiskId
	}
	return ""
}

func (x *Device) GetHardwareUUID() string {
	if x != nil {
		return x.HardwareUUID
	}
	return ""
}

func (x *Device) GetBootUUID() string {
	if x != nil {
		return x.BootUUID
	}
	return ""
}

func (x *Device) GetMACAddress() []byte {
	if x != nil {
		return x.MACAddress
	}
	return nil
}

func (x *Device) GetROM() []byte {
	if x != nil {
		return x.ROM
	}
	return nil
}

func (x *Device) GetMLB() string {
	if x != nil {
		return x.MLB
	}
	return ""
}

func (x *Device) GetKGq3489Ugfi() []byte {
	if x != nil {
		return x.KGq3489Ugfi
	}
	return nil
}

func (x *Device) GetKFyp98Tpgj() []byte {
	if x != nil {
		return x.KFyp98Tpgj
	}
	return nil
}

func (x *Device) GetKkbjfrfpoJU() []byte {
	if x != nil {
		return x.KkbjfrfpoJU
	}
	return nil
}

func (x *Device) GetKoycqAZloTNDm() []byte {
	if x != nil {
		return x.KoycqAZloTNDm
	}
	return nil
}

func (x *Device) GetKabKPld1EcMni() []byte {
	if x != nil {
		return x.KabKPld1EcMni
	}
	return nil
}

func (x *Device) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *Device) GetIMEI() string {
	if x != nil {
		return x.IMEI
	}
	return ""
}

func (x *Device) GetUniqueChipId() uint64 {
	if x != nil {
		return x.UniqueChipId
	}
	return 0
}

func (x *Device) GetUniqueDeviceId() string {
	if x != nil {
		return x.UniqueDeviceId
	}
	return ""
}

func (x *Device) GetWifiAddress() string {
	if x != nil {
		return x.WifiAddress
	}
	return ""
}

func (x *Device) GetBluetoothAddress() string {
	if x != nil {
		return x.BluetoothAddress
	}
	return ""
}

func (x *Device) GetSecureElementSN() string {
	if x != nil {
		return x.SecureElementSN
	}
	return ""
}

func (x *Device) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

func (x *Device) GetProductVersion() string {
	if x != nil {
		return x.ProductVersion
	}
	return ""
}

func (x *Device) GetFairplayKeyData() []byte {
	if x != nil {
		return x.FairplayKeyData
	}
	return nil
}

func (x *Device) GetADI() []byte {
	if x != nil {
		return x.ADI
	}
	return nil
}

func (x *Device) GetAPTicket() []byte {
	if x != nil {
		return x.APTicket
	}
	return nil
}

func (x *Device) GetSUInfo() []byte {
	if x != nil {
		return x.SUInfo
	}
	return nil
}

// 初始化请求
type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          InitializeType         `protobuf:"varint,1,opt,name=type,proto3,enum=icrypto.InitializeType" json:"type,omitempty"`
	Device        *Device                `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Controls      []string               `protobuf:"bytes,3,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeRequest) GetType() InitializeType {
	if x != nil {
		return x.Type
	}
	return InitializeType_AUTO
}

func (x *InitializeRequest) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *InitializeRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// 初始化响应
type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_crypto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{2}
}

func (x *InitializeResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

// 结束请求
type FinalizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Controls      []string               `protobuf:"bytes,1,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeRequest) Reset() {
	*x = FinalizeRequest{}
	mi := &file_crypto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeRequest) ProtoMessage() {}

func (x *FinalizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeRequest.ProtoReflect.Descriptor instead.
func (*FinalizeRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{3}
}

func (x *FinalizeRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// 结束响应
type FinalizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeResponse) Reset() {
	*x = FinalizeResponse{}
	mi := &file_crypto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeResponse) ProtoMessage() {}

func (x *FinalizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeResponse.ProtoReflect.Descriptor instead.
func (*FinalizeResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{4}
}

// DRM 激活握手请求
type ActivationDRMHandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Controls      []string               `protobuf:"bytes,1,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivationDRMHandshakeRequest) Reset() {
	*x = ActivationDRMHandshakeRequest{}
	mi := &file_crypto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDRMHandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDRMHandshakeRequest) ProtoMessage() {}

func (x *ActivationDRMHandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDRMHandshakeRequest.ProtoReflect.Descriptor instead.
func (*ActivationDRMHandshakeRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{5}
}

func (x *ActivationDRMHandshakeRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// DRM 激活握手响应
type ActivationDRMHandshakeResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	CollectionBlob          []byte                 `protobuf:"bytes,1,opt,name=collection_blob,json=collectionBlob,proto3" json:"collection_blob,omitempty"`
	HandshakeRequestMessage []byte                 `protobuf:"bytes,2,opt,name=handshake_request_message,json=handshakeRequestMessage,proto3" json:"handshake_request_message,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ActivationDRMHandshakeResponse) Reset() {
	*x = ActivationDRMHandshakeResponse{}
	mi := &file_crypto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDRMHandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDRMHandshakeResponse) ProtoMessage() {}

func (x *ActivationDRMHandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDRMHandshakeResponse.ProtoReflect.Descriptor instead.
func (*ActivationDRMHandshakeResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{6}
}

func (x *ActivationDRMHandshakeResponse) GetCollectionBlob() []byte {
	if x != nil {
		return x.CollectionBlob
	}
	return nil
}

func (x *ActivationDRMHandshakeResponse) GetHandshakeRequestMessage() []byte {
	if x != nil {
		return x.HandshakeRequestMessage
	}
	return nil
}

// DRM 激活处理请求
type ActivationDRMProcessRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SUInfo                   []byte                 `protobuf:"bytes,1,opt,name=SUInfo,proto3" json:"SUInfo,omitempty"`
	HandshakeResponseMessage []byte                 `protobuf:"bytes,2,opt,name=handshake_response_message,json=handshakeResponseMessage,proto3" json:"handshake_response_message,omitempty"`
	ServerKP                 []byte                 `protobuf:"bytes,3,opt,name=serverKP,proto3" json:"serverKP,omitempty"`
	Controls                 []string               `protobuf:"bytes,4,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ActivationDRMProcessRequest) Reset() {
	*x = ActivationDRMProcessRequest{}
	mi := &file_crypto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDRMProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDRMProcessRequest) ProtoMessage() {}

func (x *ActivationDRMProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDRMProcessRequest.ProtoReflect.Descriptor instead.
func (*ActivationDRMProcessRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{7}
}

func (x *ActivationDRMProcessRequest) GetSUInfo() []byte {
	if x != nil {
		return x.SUInfo
	}
	return nil
}

func (x *ActivationDRMProcessRequest) GetHandshakeResponseMessage() []byte {
	if x != nil {
		return x.HandshakeResponseMessage
	}
	return nil
}

func (x *ActivationDRMProcessRequest) GetServerKP() []byte {
	if x != nil {
		return x.ServerKP
	}
	return nil
}

func (x *ActivationDRMProcessRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// DRM 激活处理响应
type ActivationDRMProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UIK           []byte                 `protobuf:"bytes,1,opt,name=UIK,proto3" json:"UIK,omitempty"`
	RK            []byte                 `protobuf:"bytes,2,opt,name=RK,proto3" json:"RK,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivationDRMProcessResponse) Reset() {
	*x = ActivationDRMProcessResponse{}
	mi := &file_crypto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDRMProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDRMProcessResponse) ProtoMessage() {}

func (x *ActivationDRMProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDRMProcessResponse.ProtoReflect.Descriptor instead.
func (*ActivationDRMProcessResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{8}
}

func (x *ActivationDRMProcessResponse) GetUIK() []byte {
	if x != nil {
		return x.UIK
	}
	return nil
}

func (x *ActivationDRMProcessResponse) GetRK() []byte {
	if x != nil {
		return x.RK
	}
	return nil
}

// DRM 激活签名请求
type ActivationDRMSignatureRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActivationInfoXml []byte                 `protobuf:"bytes,1,opt,name=activation_info_xml,json=activationInfoXml,proto3" json:"activation_info_xml,omitempty"`
	Controls          []string               `protobuf:"bytes,2,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActivationDRMSignatureRequest) Reset() {
	*x = ActivationDRMSignatureRequest{}
	mi := &file_crypto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDRMSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDRMSignatureRequest) ProtoMessage() {}

func (x *ActivationDRMSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDRMSignatureRequest.ProtoReflect.Descriptor instead.
func (*ActivationDRMSignatureRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{9}
}

func (x *ActivationDRMSignatureRequest) GetActivationInfoXml() []byte {
	if x != nil {
		return x.ActivationInfoXml
	}
	return nil
}

func (x *ActivationDRMSignatureRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// DRM 激活签名响应
type ActivationDRMSignatureResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FairplayCertChain []byte                 `protobuf:"bytes,1,opt,name=fairplay_cert_chain,json=fairplayCertChain,proto3" json:"fairplay_cert_chain,omitempty"`
	FairplaySignature []byte                 `protobuf:"bytes,2,opt,name=fairplay_signature,json=fairplaySignature,proto3" json:"fairplay_signature,omitempty"`
	RKSignature       []byte                 `protobuf:"bytes,3,opt,name=RKSignature,proto3" json:"RKSignature,omitempty"`
	SignActRequest    []byte                 `protobuf:"bytes,4,opt,name=sign_act_request,json=signActRequest,proto3" json:"sign_act_request,omitempty"`
	ServerKP          []byte                 `protobuf:"bytes,5,opt,name=serverKP,proto3" json:"serverKP,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActivationDRMSignatureResponse) Reset() {
	*x = ActivationDRMSignatureResponse{}
	mi := &file_crypto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDRMSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDRMSignatureResponse) ProtoMessage() {}

func (x *ActivationDRMSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDRMSignatureResponse.ProtoReflect.Descriptor instead.
func (*ActivationDRMSignatureResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{10}
}

func (x *ActivationDRMSignatureResponse) GetFairplayCertChain() []byte {
	if x != nil {
		return x.FairplayCertChain
	}
	return nil
}

func (x *ActivationDRMSignatureResponse) GetFairplaySignature() []byte {
	if x != nil {
		return x.FairplaySignature
	}
	return nil
}

func (x *ActivationDRMSignatureResponse) GetRKSignature() []byte {
	if x != nil {
		return x.RKSignature
	}
	return nil
}

func (x *ActivationDRMSignatureResponse) GetSignActRequest() []byte {
	if x != nil {
		return x.SignActRequest
	}
	return nil
}

func (x *ActivationDRMSignatureResponse) GetServerKP() []byte {
	if x != nil {
		return x.ServerKP
	}
	return nil
}

// 旧版激活请求
type ActivationDeprecatedRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActivationInfoXml []byte                 `protobuf:"bytes,1,opt,name=activation_info_xml,json=activationInfoXml,proto3" json:"activation_info_xml,omitempty"`
	Controls          []string               `protobuf:"bytes,2,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActivationDeprecatedRequest) Reset() {
	*x = ActivationDeprecatedRequest{}
	mi := &file_crypto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDeprecatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDeprecatedRequest) ProtoMessage() {}

func (x *ActivationDeprecatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDeprecatedRequest.ProtoReflect.Descriptor instead.
func (*ActivationDeprecatedRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{11}
}

func (x *ActivationDeprecatedRequest) GetActivationInfoXml() []byte {
	if x != nil {
		return x.ActivationInfoXml
	}
	return nil
}

func (x *ActivationDeprecatedRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// 旧版激活响应
type ActivationDeprecatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sign          []byte                 `protobuf:"bytes,1,opt,name=sign,proto3" json:"sign,omitempty"`
	Cert          []byte                 `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivationDeprecatedResponse) Reset() {
	*x = ActivationDeprecatedResponse{}
	mi := &file_crypto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationDeprecatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationDeprecatedResponse) ProtoMessage() {}

func (x *ActivationDeprecatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationDeprecatedResponse.ProtoReflect.Descriptor instead.
func (*ActivationDeprecatedResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{12}
}

func (x *ActivationDeprecatedResponse) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (x *ActivationDeprecatedResponse) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

// 激活记录请求
type ActivationRecordRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Unbrick                 bool                   `protobuf:"varint,1,opt,name=unbrick,proto3" json:"unbrick,omitempty"`
	AccountTokenCertificate []byte                 `protobuf:"bytes,2,opt,name=account_token_certificate,json=accountTokenCertificate,proto3" json:"account_token_certificate,omitempty"`
	DeviceCertificate       []byte                 `protobuf:"bytes,3,opt,name=device_certificate,json=deviceCertificate,proto3" json:"device_certificate,omitempty"`
	RegulatoryInfo          []byte                 `protobuf:"bytes,4,opt,name=regulatory_info,json=regulatoryInfo,proto3" json:"regulatory_info,omitempty"`
	FairplayKeyData         []byte                 `protobuf:"bytes,5,opt,name=fairplay_key_data,json=fairplayKeyData,proto3" json:"fairplay_key_data,omitempty"`
	AccountToken            []byte                 `protobuf:"bytes,6,opt,name=account_token,json=accountToken,proto3" json:"account_token,omitempty"`
	AccountTokenSignature   []byte                 `protobuf:"bytes,7,opt,name=account_token_signature,json=accountTokenSignature,proto3" json:"account_token_signature,omitempty"`
	UniqueDeviceCertificate []byte                 `protobuf:"bytes,8,opt,name=unique_device_certificate,json=uniqueDeviceCertificate,proto3" json:"unique_device_certificate,omitempty"`
	Controls                []string               `protobuf:"bytes,9,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ActivationRecordRequest) Reset() {
	*x = ActivationRecordRequest{}
	mi := &file_crypto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationRecordRequest) ProtoMessage() {}

func (x *ActivationRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationRecordRequest.ProtoReflect.Descriptor instead.
func (*ActivationRecordRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{13}
}

func (x *ActivationRecordRequest) GetUnbrick() bool {
	if x != nil {
		return x.Unbrick
	}
	return false
}

func (x *ActivationRecordRequest) GetAccountTokenCertificate() []byte {
	if x != nil {
		return x.AccountTokenCertificate
	}
	return nil
}

func (x *ActivationRecordRequest) GetDeviceCertificate() []byte {
	if x != nil {
		return x.DeviceCertificate
	}
	return nil
}

func (x *ActivationRecordRequest) GetRegulatoryInfo() []byte {
	if x != nil {
		return x.RegulatoryInfo
	}
	return nil
}

func (x *ActivationRecordRequest) GetFairplayKeyData() []byte {
	if x != nil {
		return x.FairplayKeyData
	}
	return nil
}

func (x *ActivationRecordRequest) GetAccountToken() []byte {
	if x != nil {
		return x.AccountToken
	}
	return nil
}

func (x *ActivationRecordRequest) GetAccountTokenSignature() []byte {
	if x != nil {
		return x.AccountTokenSignature
	}
	return nil
}

func (x *ActivationRecordRequest) GetUniqueDeviceCertificate() []byte {
	if x != nil {
		return x.UniqueDeviceCertificate
	}
	return nil
}

func (x *ActivationRecordRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// 激活记录响应
type ActivationRecordResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubCAKey       []byte                 `protobuf:"bytes,1,opt,name=subCAKey,proto3" json:"subCAKey,omitempty"`
	AttestationKey []byte                 `protobuf:"bytes,2,opt,name=attestation_key,json=attestationKey,proto3" json:"attestation_key,omitempty"`
	UIK            []byte                 `protobuf:"bytes,3,opt,name=UIK,proto3" json:"UIK,omitempty"`
	RK             []byte                 `protobuf:"bytes,4,opt,name=RK,proto3" json:"RK,omitempty"`
	PscSui         []byte                 `protobuf:"bytes,5,opt,name=psc_sui,json=pscSui,proto3" json:"psc_sui,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActivationRecordResponse) Reset() {
	*x = ActivationRecordResponse{}
	mi := &file_crypto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationRecordResponse) ProtoMessage() {}

func (x *ActivationRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationRecordResponse.ProtoReflect.Descriptor instead.
func (*ActivationRecordResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{14}
}

func (x *ActivationRecordResponse) GetSubCAKey() []byte {
	if x != nil {
		return x.SubCAKey
	}
	return nil
}

func (x *ActivationRecordResponse) GetAttestationKey() []byte {
	if x != nil {
		return x.AttestationKey
	}
	return nil
}

func (x *ActivationRecordResponse) GetUIK() []byte {
	if x != nil {
		return x.UIK
	}
	return nil
}

func (x *ActivationRecordResponse) GetRK() []byte {
	if x != nil {
		return x.RK
	}
	return nil
}

func (x *ActivationRecordResponse) GetPscSui() []byte {
	if x != nil {
		return x.PscSui
	}
	return nil
}

// ADI 开始配置请求
type ADIStartProvisioningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DSID          int64                  `protobuf:"varint,1,opt,name=DSID,proto3" json:"DSID,omitempty"`
	SPIM          []byte                 `protobuf:"bytes,2,opt,name=SPIM,proto3" json:"SPIM,omitempty"`
	Controls      []string               `protobuf:"bytes,3,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADIStartProvisioningRequest) Reset() {
	*x = ADIStartProvisioningRequest{}
	mi := &file_crypto_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADIStartProvisioningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADIStartProvisioningRequest) ProtoMessage() {}

func (x *ADIStartProvisioningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADIStartProvisioningRequest.ProtoReflect.Descriptor instead.
func (*ADIStartProvisioningRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{15}
}

func (x *ADIStartProvisioningRequest) GetDSID() int64 {
	if x != nil {
		return x.DSID
	}
	return 0
}

func (x *ADIStartProvisioningRequest) GetSPIM() []byte {
	if x != nil {
		return x.SPIM
	}
	return nil
}

func (x *ADIStartProvisioningRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// ADI 开始配置响应
type ADIStartProvisioningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       uint64                 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	CPIM          []byte                 `protobuf:"bytes,2,opt,name=CPIM,proto3" json:"CPIM,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADIStartProvisioningResponse) Reset() {
	*x = ADIStartProvisioningResponse{}
	mi := &file_crypto_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADIStartProvisioningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADIStartProvisioningResponse) ProtoMessage() {}

func (x *ADIStartProvisioningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADIStartProvisioningResponse.ProtoReflect.Descriptor instead.
func (*ADIStartProvisioningResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{16}
}

func (x *ADIStartProvisioningResponse) GetSession() uint64 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *ADIStartProvisioningResponse) GetCPIM() []byte {
	if x != nil {
		return x.CPIM
	}
	return nil
}

// ADI 结束配置请求
type ADIEndProvisioningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       uint64                 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	DSID          int64                  `protobuf:"varint,2,opt,name=DSID,proto3" json:"DSID,omitempty"`
	RINFO         int64                  `protobuf:"varint,3,opt,name=RINFO,proto3" json:"RINFO,omitempty"`
	PTM           []byte                 `protobuf:"bytes,4,opt,name=PTM,proto3" json:"PTM,omitempty"`
	TK            []byte                 `protobuf:"bytes,5,opt,name=TK,proto3" json:"TK,omitempty"`
	ADI           []byte                 `protobuf:"bytes,6,opt,name=ADI,proto3" json:"ADI,omitempty"`
	Controls      []string               `protobuf:"bytes,7,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADIEndProvisioningRequest) Reset() {
	*x = ADIEndProvisioningRequest{}
	mi := &file_crypto_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADIEndProvisioningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADIEndProvisioningRequest) ProtoMessage() {}

func (x *ADIEndProvisioningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADIEndProvisioningRequest.ProtoReflect.Descriptor instead.
func (*ADIEndProvisioningRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{17}
}

func (x *ADIEndProvisioningRequest) GetSession() uint64 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *ADIEndProvisioningRequest) GetDSID() int64 {
	if x != nil {
		return x.DSID
	}
	return 0
}

func (x *ADIEndProvisioningRequest) GetRINFO() int64 {
	if x != nil {
		return x.RINFO
	}
	return 0
}

func (x *ADIEndProvisioningRequest) GetPTM() []byte {
	if x != nil {
		return x.PTM
	}
	return nil
}

func (x *ADIEndProvisioningRequest) GetTK() []byte {
	if x != nil {
		return x.TK
	}
	return nil
}

func (x *ADIEndProvisioningRequest) GetADI() []byte {
	if x != nil {
		return x.ADI
	}
	return nil
}

func (x *ADIEndProvisioningRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// ADI 结束配置响应
type ADIEndProvisioningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MID           []byte                 `protobuf:"bytes,1,opt,name=MID,proto3" json:"MID,omitempty"`
	OTP           []byte                 `protobuf:"bytes,2,opt,name=OTP,proto3" json:"OTP,omitempty"`
	ADI           []byte                 `protobuf:"bytes,3,opt,name=ADI,proto3" json:"ADI,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADIEndProvisioningResponse) Reset() {
	*x = ADIEndProvisioningResponse{}
	mi := &file_crypto_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADIEndProvisioningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADIEndProvisioningResponse) ProtoMessage() {}

func (x *ADIEndProvisioningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADIEndProvisioningResponse.ProtoReflect.Descriptor instead.
func (*ADIEndProvisioningResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{18}
}

func (x *ADIEndProvisioningResponse) GetMID() []byte {
	if x != nil {
		return x.MID
	}
	return nil
}

func (x *ADIEndProvisioningResponse) GetOTP() []byte {
	if x != nil {
		return x.OTP
	}
	return nil
}

func (x *ADIEndProvisioningResponse) GetADI() []byte {
	if x != nil {
		return x.ADI
	}
	return nil
}

// ADI 生成登录码请求
type ADIGenerateLoginCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DSID          int64                  `protobuf:"varint,1,opt,name=DSID,proto3" json:"DSID,omitempty"`
	ADI           []byte                 `protobuf:"bytes,2,opt,name=ADI,proto3" json:"ADI,omitempty"`
	Controls      []string               `protobuf:"bytes,3,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADIGenerateLoginCodeRequest) Reset() {
	*x = ADIGenerateLoginCodeRequest{}
	mi := &file_crypto_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADIGenerateLoginCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADIGenerateLoginCodeRequest) ProtoMessage() {}

func (x *ADIGenerateLoginCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADIGenerateLoginCodeRequest.ProtoReflect.Descriptor instead.
func (*ADIGenerateLoginCodeRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{19}
}

func (x *ADIGenerateLoginCodeRequest) GetDSID() int64 {
	if x != nil {
		return x.DSID
	}
	return 0
}

func (x *ADIGenerateLoginCodeRequest) GetADI() []byte {
	if x != nil {
		return x.ADI
	}
	return nil
}

func (x *ADIGenerateLoginCodeRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// ADI 生成登录码响应
type ADIGenerateLoginCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	LoginCode     uint32                 `protobuf:"varint,2,opt,name=login_code,json=loginCode,proto3" json:"login_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADIGenerateLoginCodeResponse) Reset() {
	*x = ADIGenerateLoginCodeResponse{}
	mi := &file_crypto_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADIGenerateLoginCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADIGenerateLoginCodeResponse) ProtoMessage() {}

func (x *ADIGenerateLoginCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADIGenerateLoginCodeResponse.ProtoReflect.Descriptor instead.
func (*ADIGenerateLoginCodeResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{20}
}

func (x *ADIGenerateLoginCodeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ADIGenerateLoginCodeResponse) GetLoginCode() uint32 {
	if x != nil {
		return x.LoginCode
	}
	return 0
}

// Absinthe Hello 请求
type AbsintheHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          int32                  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Controls      []string               `protobuf:"bytes,2,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsintheHelloRequest) Reset() {
	*x = AbsintheHelloRequest{}
	mi := &file_crypto_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheHelloRequest) ProtoMessage() {}

func (x *AbsintheHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheHelloRequest.ProtoReflect.Descriptor instead.
func (*AbsintheHelloRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{21}
}

func (x *AbsintheHelloRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *AbsintheHelloRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// Absinthe Hello 响应
type AbsintheHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HelloMessage  []byte                 `protobuf:"bytes,1,opt,name=hello_message,json=helloMessage,proto3" json:"hello_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsintheHelloResponse) Reset() {
	*x = AbsintheHelloResponse{}
	mi := &file_crypto_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheHelloResponse) ProtoMessage() {}

func (x *AbsintheHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheHelloResponse.ProtoReflect.Descriptor instead.
func (*AbsintheHelloResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{22}
}

func (x *AbsintheHelloResponse) GetHelloMessage() []byte {
	if x != nil {
		return x.HelloMessage
	}
	return nil
}

// Absinthe 添加选项请求
type AbsintheAddOptionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BikKey               []byte                 `protobuf:"bytes,1,opt,name=bik_key,json=bikKey,proto3" json:"bik_key,omitempty"`
	BaaCert              []byte                 `protobuf:"bytes,2,opt,name=baa_cert,json=baaCert,proto3" json:"baa_cert,omitempty"`
	IntermediateRootCert []byte                 `protobuf:"bytes,3,opt,name=intermediate_root_cert,json=intermediateRootCert,proto3" json:"intermediate_root_cert,omitempty"`
	Controls             []string               `protobuf:"bytes,4,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AbsintheAddOptionRequest) Reset() {
	*x = AbsintheAddOptionRequest{}
	mi := &file_crypto_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheAddOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheAddOptionRequest) ProtoMessage() {}

func (x *AbsintheAddOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheAddOptionRequest.ProtoReflect.Descriptor instead.
func (*AbsintheAddOptionRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{23}
}

func (x *AbsintheAddOptionRequest) GetBikKey() []byte {
	if x != nil {
		return x.BikKey
	}
	return nil
}

func (x *AbsintheAddOptionRequest) GetBaaCert() []byte {
	if x != nil {
		return x.BaaCert
	}
	return nil
}

func (x *AbsintheAddOptionRequest) GetIntermediateRootCert() []byte {
	if x != nil {
		return x.IntermediateRootCert
	}
	return nil
}

func (x *AbsintheAddOptionRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// Absinthe 添加选项响应
type AbsintheAddOptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsintheAddOptionResponse) Reset() {
	*x = AbsintheAddOptionResponse{}
	mi := &file_crypto_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheAddOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheAddOptionResponse) ProtoMessage() {}

func (x *AbsintheAddOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheAddOptionResponse.ProtoReflect.Descriptor instead.
func (*AbsintheAddOptionResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{24}
}

// Absinthe 激活会话请求
type AbsintheActivateSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ValidationData []byte                 `protobuf:"bytes,1,opt,name=validation_data,json=validationData,proto3" json:"validation_data,omitempty"`
	ServerKey      []byte                 `protobuf:"bytes,2,opt,name=server_key,json=serverKey,proto3" json:"server_key,omitempty"`
	Controls       []string               `protobuf:"bytes,3,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AbsintheActivateSessionRequest) Reset() {
	*x = AbsintheActivateSessionRequest{}
	mi := &file_crypto_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheActivateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheActivateSessionRequest) ProtoMessage() {}

func (x *AbsintheActivateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheActivateSessionRequest.ProtoReflect.Descriptor instead.
func (*AbsintheActivateSessionRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{25}
}

func (x *AbsintheActivateSessionRequest) GetValidationData() []byte {
	if x != nil {
		return x.ValidationData
	}
	return nil
}

func (x *AbsintheActivateSessionRequest) GetServerKey() []byte {
	if x != nil {
		return x.ServerKey
	}
	return nil
}

func (x *AbsintheActivateSessionRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// Absinthe 激活会话响应
type AbsintheActivateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsintheActivateSessionResponse) Reset() {
	*x = AbsintheActivateSessionResponse{}
	mi := &file_crypto_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheActivateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheActivateSessionResponse) ProtoMessage() {}

func (x *AbsintheActivateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheActivateSessionResponse.ProtoReflect.Descriptor instead.
func (*AbsintheActivateSessionResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{26}
}

// Absinthe 签名数据请求
type AbsintheSignDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignData      []byte                 `protobuf:"bytes,1,opt,name=sign_data,json=signData,proto3" json:"sign_data,omitempty"`
	Controls      []string               `protobuf:"bytes,2,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsintheSignDataRequest) Reset() {
	*x = AbsintheSignDataRequest{}
	mi := &file_crypto_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheSignDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheSignDataRequest) ProtoMessage() {}

func (x *AbsintheSignDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheSignDataRequest.ProtoReflect.Descriptor instead.
func (*AbsintheSignDataRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{27}
}

func (x *AbsintheSignDataRequest) GetSignData() []byte {
	if x != nil {
		return x.SignData
	}
	return nil
}

func (x *AbsintheSignDataRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// Absinthe 签名数据响应
type AbsintheSignDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	OutServKey    []byte                 `protobuf:"bytes,2,opt,name=out_serv_key,json=outServKey,proto3" json:"out_serv_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsintheSignDataResponse) Reset() {
	*x = AbsintheSignDataResponse{}
	mi := &file_crypto_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsintheSignDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsintheSignDataResponse) ProtoMessage() {}

func (x *AbsintheSignDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsintheSignDataResponse.ProtoReflect.Descriptor instead.
func (*AbsintheSignDataResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{28}
}

func (x *AbsintheSignDataResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AbsintheSignDataResponse) GetOutServKey() []byte {
	if x != nil {
		return x.OutServKey
	}
	return nil
}

// Identity 会话请求
type IdentitySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cert          []byte                 `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Controls      []string               `protobuf:"bytes,2,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentitySessionRequest) Reset() {
	*x = IdentitySessionRequest{}
	mi := &file_crypto_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySessionRequest) ProtoMessage() {}

func (x *IdentitySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySessionRequest.ProtoReflect.Descriptor instead.
func (*IdentitySessionRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{29}
}

func (x *IdentitySessionRequest) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *IdentitySessionRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// Identity 会话响应
type IdentitySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       []byte                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentitySessionResponse) Reset() {
	*x = IdentitySessionResponse{}
	mi := &file_crypto_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySessionResponse) ProtoMessage() {}

func (x *IdentitySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySessionResponse.ProtoReflect.Descriptor instead.
func (*IdentitySessionResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{30}
}

func (x *IdentitySessionResponse) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

// Identity 验证请求
type IdentityValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      []byte                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	SignData      []byte                 `protobuf:"bytes,2,opt,name=sign_data,json=signData,proto3" json:"sign_data,omitempty"`
	Controls      []string               `protobuf:"bytes,3,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityValidationRequest) Reset() {
	*x = IdentityValidationRequest{}
	mi := &file_crypto_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityValidationRequest) ProtoMessage() {}

func (x *IdentityValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityValidationRequest.ProtoReflect.Descriptor instead.
func (*IdentityValidationRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{31}
}

func (x *IdentityValidationRequest) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *IdentityValidationRequest) GetSignData() []byte {
	if x != nil {
		return x.SignData
	}
	return nil
}

func (x *IdentityValidationRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// Identity 验证响应
type IdentityValidationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ValidationData []byte                 `protobuf:"bytes,1,opt,name=validation_data,json=validationData,proto3" json:"validation_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IdentityValidationResponse) Reset() {
	*x = IdentityValidationResponse{}
	mi := &file_crypto_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityValidationResponse) ProtoMessage() {}

func (x *IdentityValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityValidationResponse.ProtoReflect.Descriptor instead.
func (*IdentityValidationResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{32}
}

func (x *IdentityValidationResponse) GetValidationData() []byte {
	if x != nil {
		return x.ValidationData
	}
	return nil
}

// SAP 交换请求
type SAPExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Controls      []string               `protobuf:"bytes,2,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPExchangeRequest) Reset() {
	*x = SAPExchangeRequest{}
	mi := &file_crypto_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPExchangeRequest) ProtoMessage() {}

func (x *SAPExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPExchangeRequest.ProtoReflect.Descriptor instead.
func (*SAPExchangeRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{33}
}

func (x *SAPExchangeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SAPExchangeRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// SAP 交换响应
type SAPExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeData  []byte                 `protobuf:"bytes,1,opt,name=exchange_data,json=exchangeData,proto3" json:"exchange_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPExchangeResponse) Reset() {
	*x = SAPExchangeResponse{}
	mi := &file_crypto_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPExchangeResponse) ProtoMessage() {}

func (x *SAPExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPExchangeResponse.ProtoReflect.Descriptor instead.
func (*SAPExchangeResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{34}
}

func (x *SAPExchangeResponse) GetExchangeData() []byte {
	if x != nil {
		return x.ExchangeData
	}
	return nil
}

// SAP 质数签名请求
type SAPSignPrimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignData      []byte                 `protobuf:"bytes,1,opt,name=sign_data,json=signData,proto3" json:"sign_data,omitempty"`
	Controls      []string               `protobuf:"bytes,2,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPSignPrimeRequest) Reset() {
	*x = SAPSignPrimeRequest{}
	mi := &file_crypto_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPSignPrimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPSignPrimeRequest) ProtoMessage() {}

func (x *SAPSignPrimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPSignPrimeRequest.ProtoReflect.Descriptor instead.
func (*SAPSignPrimeRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{35}
}

func (x *SAPSignPrimeRequest) GetSignData() []byte {
	if x != nil {
		return x.SignData
	}
	return nil
}

func (x *SAPSignPrimeRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// SAP 质数签名响应
type SAPSignPrimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPSignPrimeResponse) Reset() {
	*x = SAPSignPrimeResponse{}
	mi := &file_crypto_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPSignPrimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPSignPrimeResponse) ProtoMessage() {}

func (x *SAPSignPrimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPSignPrimeResponse.ProtoReflect.Descriptor instead.
func (*SAPSignPrimeResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{36}
}

func (x *SAPSignPrimeResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// SAP 质数验证请求
type SAPVerifyPrimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Controls      []string               `protobuf:"bytes,2,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPVerifyPrimeRequest) Reset() {
	*x = SAPVerifyPrimeRequest{}
	mi := &file_crypto_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPVerifyPrimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPVerifyPrimeRequest) ProtoMessage() {}

func (x *SAPVerifyPrimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPVerifyPrimeRequest.ProtoReflect.Descriptor instead.
func (*SAPVerifyPrimeRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{37}
}

func (x *SAPVerifyPrimeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SAPVerifyPrimeRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// SAP 质数验证响应
type SAPVerifyPrimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPVerifyPrimeResponse) Reset() {
	*x = SAPVerifyPrimeResponse{}
	mi := &file_crypto_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPVerifyPrimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPVerifyPrimeResponse) ProtoMessage() {}

func (x *SAPVerifyPrimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPVerifyPrimeResponse.ProtoReflect.Descriptor instead.
func (*SAPVerifyPrimeResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{38}
}

// SAP 签名请求
type SAPSignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignData      []byte                 `protobuf:"bytes,1,opt,name=sign_data,json=signData,proto3" json:"sign_data,omitempty"`
	Controls      []string               `protobuf:"bytes,2,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPSignRequest) Reset() {
	*x = SAPSignRequest{}
	mi := &file_crypto_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPSignRequest) ProtoMessage() {}

func (x *SAPSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPSignRequest.ProtoReflect.Descriptor instead.
func (*SAPSignRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{39}
}

func (x *SAPSignRequest) GetSignData() []byte {
	if x != nil {
		return x.SignData
	}
	return nil
}

func (x *SAPSignRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// SAP 签名响应
type SAPSignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPSignResponse) Reset() {
	*x = SAPSignResponse{}
	mi := &file_crypto_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPSignResponse) ProtoMessage() {}

func (x *SAPSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPSignResponse.ProtoReflect.Descriptor instead.
func (*SAPSignResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{40}
}

func (x *SAPSignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// SAP 验证请求
type SAPVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Controls      []string               `protobuf:"bytes,3,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPVerifyRequest) Reset() {
	*x = SAPVerifyRequest{}
	mi := &file_crypto_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPVerifyRequest) ProtoMessage() {}

func (x *SAPVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPVerifyRequest.ProtoReflect.Descriptor instead.
func (*SAPVerifyRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{41}
}

func (x *SAPVerifyRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SAPVerifyRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SAPVerifyRequest) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

// SAP 验证响应
type SAPVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAPVerifyResponse) Reset() {
	*x = SAPVerifyResponse{}
	mi := &file_crypto_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAPVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAPVerifyResponse) ProtoMessage() {}

func (x *SAPVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAPVerifyResponse.ProtoReflect.Descriptor instead.
func (*SAPVerifyResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{42}
}

var File_crypto_proto protoreflect.FileDescriptor

const file_crypto_proto_rawDesc = "" +
	"\n" +
	"\fcrypto.proto\x12\aicrypto\x1a\x1cgoogle/api/annotations.proto\"\xd8\a\n" +
	"\x06Device\x12(\n" +
	"\aos_type\x18\x01 \x01(\x0e2\x0f.icrypto.OSEnumR\x06osType\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1f\n" +
	"\vos_revision\x18\x04 \x01(\x04R\n" +
	"osRevision\x12\x1d\n" +
	"\n" +
	"os_version\x18\x05 \x01(\tR\tosVersion\x12\x19\n" +
	"\bboard_id\x18\x06 \x01(\tR\aboardId\x12\x17\n" +
	"\adisk_id\x18\a \x01(\tR\x06diskId\x12\"\n" +
	"\fhardwareUUID\x18\b \x01(\tR\fhardwareUUID\x12\x1a\n" +
	"\bbootUUID\x18\t \x01(\tR\bbootUUID\x12\x1e\n" +
	"\n" +
	"MACAddress\x18\n" +
	" \x01(\fR\n" +
	"MACAddress\x12\x10\n" +
	"\x03ROM\x18\v \x01(\fR\x03ROM\x12\x10\n" +
	"\x03MLB\x18\f \x01(\tR\x03MLB\x12 \n" +
	"\vkGq3489ugfi\x18\r \x01(\fR\vkGq3489ugfi\x12\x1e\n" +
	"\n" +
	"kFyp98tpgj\x18\x0e \x01(\fR\n" +
	"kFyp98tpgj\x12 \n" +
	"\vkkbjfrfpoJU\x18\x0f \x01(\fR\vkkbjfrfpoJU\x12$\n" +
	"\rkoycqAZloTNDm\x18\x10 \x01(\fR\rkoycqAZloTNDm\x12$\n" +
	"\rkabKPld1EcMni\x18\x11 \x01(\fR\rkabKPld1EcMni\x12!\n" +
	"\fproduct_type\x18\x12 \x01(\tR\vproductType\x12\x12\n" +
	"\x04IMEI\x18\x13 \x01(\tR\x04IMEI\x12$\n" +
	"\x0eunique_chip_id\x18\x14 \x01(\x04R\funiqueChipId\x12(\n" +
	"\x10unique_device_id\x18\x15 \x01(\tR\x0euniqueDeviceId\x12!\n" +
	"\fwifi_address\x18\x16 \x01(\tR\vwifiAddress\x12+\n" +
	"\x11bluetooth_address\x18\x17 \x01(\tR\x10bluetoothAddress\x12)\n" +
	"\x10secure_elementSN\x18\x18 \x01(\tR\x0fsecureElementSN\x12#\n" +
	"\rbuild_version\x18\x19 \x01(\tR\fbuildVersion\x12'\n" +
	"\x0fproduct_version\x18\x1a \x01(\tR\x0eproductVersion\x12*\n" +
	"\x11fairplay_key_data\x18\x1b \x01(\fR\x0ffairplayKeyData\x12\x10\n" +
	"\x03ADI\x18\x1c \x01(\fR\x03ADI\x12\x1b\n" +
	"\tAP_ticket\x18\x1d \x01(\fR\bAPTicket\x12\x16\n" +
	"\x06SUInfo\x18\x1e \x01(\fR\x06SUInfo\"\x85\x01\n" +
	"\x11InitializeRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.icrypto.InitializeTypeR\x04type\x12'\n" +
	"\x06device\x18\x02 \x01(\v2\x0f.icrypto.DeviceR\x06device\x12\x1a\n" +
	"\bcontrols\x18\x03 \x03(\tR\bcontrols\"=\n" +
	"\x12InitializeResponse\x12'\n" +
	"\x06device\x18\x01 \x01(\v2\x0f.icrypto.DeviceR\x06device\"-\n" +
	"\x0fFinalizeRequest\x12\x1a\n" +
	"\bcontrols\x18\x01 \x03(\tR\bcontrols\"\x12\n" +
	"\x10FinalizeResponse\";\n" +
	"\x1dActivationDRMHandshakeRequest\x12\x1a\n" +
	"\bcontrols\x18\x01 \x03(\tR\bcontrols\"\x85\x01\n" +
	"\x1eActivationDRMHandshakeResponse\x12'\n" +
	"\x0fcollection_blob\x18\x01 \x01(\fR\x0ecollectionBlob\x12:\n" +
	"\x19handshake_request_message\x18\x02 \x01(\fR\x17handshakeRequestMessage\"\xab\x01\n" +
	"\x1bActivationDRMProcessRequest\x12\x16\n" +
	"\x06SUInfo\x18\x01 \x01(\fR\x06SUInfo\x12<\n" +
	"\x1ahandshake_response_message\x18\x02 \x01(\fR\x18handshakeResponseMessage\x12\x1a\n" +
	"\bserverKP\x18\x03 \x01(\fR\bserverKP\x12\x1a\n" +
	"\bcontrols\x18\x04 \x03(\tR\bcontrols\"@\n" +
	"\x1cActivationDRMProcessResponse\x12\x10\n" +
	"\x03UIK\x18\x01 \x01(\fR\x03UIK\x12\x0e\n" +
	"\x02RK\x18\x02 \x01(\fR\x02RK\"k\n" +
	"\x1dActivationDRMSignatureRequest\x12.\n" +
	"\x13activation_info_xml\x18\x01 \x01(\fR\x11activationInfoXml\x12\x1a\n" +
	"\bcontrols\x18\x02 \x03(\tR\bcontrols\"\xe7\x01\n" +
	"\x1eActivationDRMSignatureResponse\x12.\n" +
	"\x13fairplay_cert_chain\x18\x01 \x01(\fR\x11fairplayCertChain\x12-\n" +
	"\x12fairplay_signature\x18\x02 \x01(\fR\x11fairplaySignature\x12 \n" +
	"\vRKSignature\x18\x03 \x01(\fR\vRKSignature\x12(\n" +
	"\x10sign_act_request\x18\x04 \x01(\fR\x0esignActRequest\x12\x1a\n" +
	"\bserverKP\x18\x05 \x01(\fR\bserverKP\"i\n" +
	"\x1bActivationDeprecatedRequest\x12.\n" +
	"\x13activation_info_xml\x18\x01 \x01(\fR\x11activationInfoXml\x12\x1a\n" +
	"\bcontrols\x18\x02 \x03(\tR\bcontrols\"F\n" +
	"\x1cActivationDeprecatedResponse\x12\x12\n" +
	"\x04sign\x18\x01 \x01(\fR\x04sign\x12\x12\n" +
	"\x04cert\x18\x02 \x01(\fR\x04cert\"\xa8\x03\n" +
	"\x17ActivationRecordRequest\x12\x18\n" +
	"\aunbrick\x18\x01 \x01(\bR\aunbrick\x12:\n" +
	"\x19account_token_certificate\x18\x02 \x01(\fR\x17accountTokenCertificate\x12-\n" +
	"\x12device_certificate\x18\x03 \x01(\fR\x11deviceCertificate\x12'\n" +
	"\x0fregulatory_info\x18\x04 \x01(\fR\x0eregulatoryInfo\x12*\n" +
	"\x11fairplay_key_data\x18\x05 \x01(\fR\x0ffairplayKeyData\x12#\n" +
	"\raccount_token\x18\x06 \x01(\fR\faccountToken\x126\n" +
	"\x17account_token_signature\x18\a \x01(\fR\x15accountTokenSignature\x12:\n" +
	"\x19unique_device_certificate\x18\b \x01(\fR\x17uniqueDeviceCertificate\x12\x1a\n" +
	"\bcontrols\x18\t \x03(\tR\bcontrols\"\x9a\x01\n" +
	"\x18ActivationRecordResponse\x12\x1a\n" +
	"\bsubCAKey\x18\x01 \x01(\fR\bsubCAKey\x12'\n" +
	"\x0fattestation_key\x18\x02 \x01(\fR\x0eattestationKey\x12\x10\n" +
	"\x03UIK\x18\x03 \x01(\fR\x03UIK\x12\x0e\n" +
	"\x02RK\x18\x04 \x01(\fR\x02RK\x12\x17\n" +
	"\apsc_sui\x18\x05 \x01(\fR\x06pscSui\"a\n" +
	"\x1bADIStartProvisioningRequest\x12\x12\n" +
	"\x04DSID\x18\x01 \x01(\x03R\x04DSID\x12\x12\n" +
	"\x04SPIM\x18\x02 \x01(\fR\x04SPIM\x12\x1a\n" +
	"\bcontrols\x18\x03 \x03(\tR\bcontrols\"L\n" +
	"\x1cADIStartProvisioningResponse\x12\x18\n" +
	"\asession\x18\x01 \x01(\x04R\asession\x12\x12\n" +
	"\x04CPIM\x18\x02 \x01(\fR\x04CPIM\"\xaf\x01\n" +
	"\x19ADIEndProvisioningRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\x04R\asession\x12\x12\n" +
	"\x04DSID\x18\x02 \x01(\x03R\x04DSID\x12\x14\n" +
	"\x05RINFO\x18\x03 \x01(\x03R\x05RINFO\x12\x10\n" +
	"\x03PTM\x18\x04 \x01(\fR\x03PTM\x12\x0e\n" +
	"\x02TK\x18\x05 \x01(\fR\x02TK\x12\x10\n" +
	"\x03ADI\x18\x06 \x01(\fR\x03ADI\x12\x1a\n" +
	"\bcontrols\x18\a \x03(\tR\bcontrols\"R\n" +
	"\x1aADIEndProvisioningResponse\x12\x10\n" +
	"\x03MID\x18\x01 \x01(\fR\x03MID\x12\x10\n" +
	"\x03OTP\x18\x02 \x01(\fR\x03OTP\x12\x10\n" +
	"\x03ADI\x18\x03 \x01(\fR\x03ADI\"_\n" +
	"\x1bADIGenerateLoginCodeRequest\x12\x12\n" +
	"\x04DSID\x18\x01 \x01(\x03R\x04DSID\x12\x10\n" +
	"\x03ADI\x18\x02 \x01(\fR\x03ADI\x12\x1a\n" +
	"\bcontrols\x18\x03 \x03(\tR\bcontrols\"Q\n" +
	"\x1cADIGenerateLoginCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1d\n" +
	"\n" +
	"login_code\x18\x02 \x01(\rR\tloginCode\"F\n" +
	"\x14AbsintheHelloRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\x05R\x04mode\x12\x1a\n" +
	"\bcontrols\x18\x02 \x03(\tR\bcontrols\"<\n" +
	"\x15AbsintheHelloResponse\x12#\n" +
	"\rhello_message\x18\x01 \x01(\fR\fhelloMessage\"\xa0\x01\n" +
	"\x18AbsintheAddOptionRequest\x12\x17\n" +
	"\abik_key\x18\x01 \x01(\fR\x06bikKey\x12\x19\n" +
	"\bbaa_cert\x18\x02 \x01(\fR\abaaCert\x124\n" +
	"\x16intermediate_root_cert\x18\x03 \x01(\fR\x14intermediateRootCert\x12\x1a\n" +
	"\bcontrols\x18\x04 \x03(\tR\bcontrols\"\x1b\n" +
	"\x19AbsintheAddOptionResponse\"\x84\x01\n" +
	"\x1eAbsintheActivateSessionRequest\x12'\n" +
	"\x0fvalidation_data\x18\x01 \x01(\fR\x0evalidationData\x12\x1d\n" +
	"\n" +
	"server_key\x18\x02 \x01(\fR\tserverKey\x12\x1a\n" +
	"\bcontrols\x18\x03 \x03(\tR\bcontrols\"!\n" +
	"\x1fAbsintheActivateSessionResponse\"R\n" +
	"\x17AbsintheSignDataRequest\x12\x1b\n" +
	"\tsign_data\x18\x01 \x01(\fR\bsignData\x12\x1a\n" +
	"\bcontrols\x18\x02 \x03(\tR\bcontrols\"Z\n" +
	"\x18AbsintheSignDataResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12 \n" +
	"\fout_serv_key\x18\x02 \x01(\fR\n" +
	"outServKey\"H\n" +
	"\x16IdentitySessionRequest\x12\x12\n" +
	"\x04cert\x18\x01 \x01(\fR\x04cert\x12\x1a\n" +
	"\bcontrols\x18\x02 \x03(\tR\bcontrols\"3\n" +
	"\x17IdentitySessionResponse\x12\x18\n" +
	"\arequest\x18\x01 \x01(\fR\arequest\"p\n" +
	"\x19IdentityValidationRequest\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\x12\x1b\n" +
	"\tsign_data\x18\x02 \x01(\fR\bsignData\x12\x1a\n" +
	"\bcontrols\x18\x03 \x03(\tR\bcontrols\"E\n" +
	"\x1aIdentityValidationResponse\x12'\n" +
	"\x0fvalidation_data\x18\x01 \x01(\fR\x0evalidationData\"D\n" +
	"\x12SAPExchangeRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bcontrols\x18\x02 \x03(\tR\bcontrols\":\n" +
	"\x13SAPExchangeResponse\x12#\n" +
	"\rexchange_data\x18\x01 \x01(\fR\fexchangeData\"N\n" +
	"\x13SAPSignPrimeRequest\x12\x1b\n" +
	"\tsign_data\x18\x01 \x01(\fR\bsignData\x12\x1a\n" +
	"\bcontrols\x18\x02 \x03(\tR\bcontrols\"4\n" +
	"\x14SAPSignPrimeResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"G\n" +
	"\x15SAPVerifyPrimeRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bcontrols\x18\x02 \x03(\tR\bcontrols\"\x18\n" +
	"\x16SAPVerifyPrimeResponse\"I\n" +
	"\x0eSAPSignRequest\x12\x1b\n" +
	"\tsign_data\x18\x01 \x01(\fR\bsignData\x12\x1a\n" +
	"\bcontrols\x18\x02 \x03(\tR\bcontrols\"/\n" +
	"\x0fSAPSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"`\n" +
	"\x10SAPVerifyRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1a\n" +
	"\bcontrols\x18\x03 \x03(\tR\bcontrols\"\x13\n" +
	"\x11SAPVerifyResponse*:\n" +
	"\x06OSEnum\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05MACOS\x10\x01\x12\a\n" +
	"\x03IOS\x10\x02\x12\v\n" +
	"\aANDROID\x10\x03*K\n" +
	"\x0eInitializeType\x12\b\n" +
	"\x04AUTO\x10\x00\x12\r\n" +
	"\tIOSARCH64\x10\x01\x12\f\n" +
	"\bIOSDRM32\x10\x02\x12\x12\n" +
	"\x0eMACOSDISABLE15\x10\x042\xe3\x13\n" +
	"\fCryptService\x12]\n" +
	"\n" +
	"Initialize\x12\x1a.icrypto.InitializeRequest\x1a\x1b.icrypto.InitializeResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/initialize\x12U\n" +
	"\bFinalize\x12\x18.icrypto.FinalizeRequest\x1a\x19.icrypto.FinalizeResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/finalize\x12\x8f\x01\n" +
	"\x16ActivationDRMHandshake\x12&.icrypto.ActivationDRMHandshakeRequest\x1a'.icrypto.ActivationDRMHandshakeResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/activation/drm/handshake\x12\x87\x01\n" +
	"\x14ActivationDRMProcess\x12$.icrypto.ActivationDRMProcessRequest\x1a%.icrypto.ActivationDRMProcessResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/activation/drm/process\x12\x8f\x01\n" +
	"\x16ActivationDRMSignature\x12&.icrypto.ActivationDRMSignatureRequest\x1a'.icrypto.ActivationDRMSignatureResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/activation/drm/signature\x12\x86\x01\n" +
	"\x14ActivationDeprecated\x12$.icrypto.ActivationDeprecatedRequest\x1a%.icrypto.ActivationDeprecatedResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/activation/deprecated\x12v\n" +
	"\x10ActivationRecord\x12 .icrypto.ActivationRecordRequest\x1a!.icrypto.ActivationRecordResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/activation/record\x12\x87\x01\n" +
	"\x14ADIStartProvisioning\x12$.icrypto.ADIStartProvisioningRequest\x1a%.icrypto.ADIStartProvisioningResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/adi/start-provisioning\x12\x7f\n" +
	"\x12ADIEndProvisioning\x12\".icrypto.ADIEndProvisioningRequest\x1a#.icrypto.ADIEndProvisioningResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/adi/end-provisioning\x12\x88\x01\n" +
	"\x14ADIGenerateLoginCode\x12$.icrypto.ADIGenerateLoginCodeRequest\x1a%.icrypto.ADIGenerateLoginCodeResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/adi/generate-login-code\x12j\n" +
	"\rAbsintheHello\x12\x1d.icrypto.AbsintheHelloRequest\x1a\x1e.icrypto.AbsintheHelloResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/absinthe/hello\x12{\n" +
	"\x11AbsintheAddOption\x12!.icrypto.AbsintheAddOptionRequest\x1a\".icrypto.AbsintheAddOptionResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/absinthe/add-option\x12\x93\x01\n" +
	"\x17AbsintheActivateSession\x12'.icrypto.AbsintheActivateSessionRequest\x1a(.icrypto.AbsintheActivateSessionResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/absinthe/activate-session\x12w\n" +
	"\x10AbsintheSignData\x12 .icrypto.AbsintheSignDataRequest\x1a!.icrypto.AbsintheSignDataResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/absinthe/sign-data\x12r\n" +
	"\x0fIdentitySession\x12\x1f.icrypto.IdentitySessionRequest\x1a .icrypto.IdentitySessionResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/identity/session\x12~\n" +
	"\x12IdentityValidation\x12\".icrypto.IdentityValidationRequest\x1a#.icrypto.IdentityValidationResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/identity/validation\x12b\n" +
	"\vSAPExchange\x12\x1b.icrypto.SAPExchangeRequest\x1a\x1c.icrypto.SAPExchangeResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/sap/exchange\x12g\n" +
	"\fSAPSignPrime\x12\x1c.icrypto.SAPSignPrimeRequest\x1a\x1d.icrypto.SAPSignPrimeResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/sap/sign-prime\x12o\n" +
	"\x0eSAPVerifyPrime\x12\x1e.icrypto.SAPVerifyPrimeRequest\x1a\x1f.icrypto.SAPVerifyPrimeResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/sap/verify-prime\x12R\n" +
	"\aSAPSign\x12\x17.icrypto.SAPSignRequest\x1a\x18.icrypto.SAPSignResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/sap/sign\x12Z\n" +
	"\tSAPVerify\x12\x19.icrypto.SAPVerifyRequest\x1a\x1a.icrypto.SAPVerifyResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/sap/verifyB\x1eZ\x1cgithub.com/zdypro888/icryptob\x06proto3"

var (
	file_crypto_proto_rawDescOnce sync.Once
	file_crypto_proto_rawDescData []byte
)

func file_crypto_proto_rawDescGZIP() []byte {
	file_crypto_proto_rawDescOnce.Do(func() {
		file_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crypto_proto_rawDesc), len(file_crypto_proto_rawDesc)))
	})
	return file_crypto_proto_rawDescData
}

var file_crypto_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_crypto_proto_goTypes = []any{
	(OSEnum)(0),                             // 0: icrypto.OSEnum
	(InitializeType)(0),                     // 1: icrypto.InitializeType
	(*Device)(nil),                          // 2: icrypto.Device
	(*InitializeRequest)(nil),               // 3: icrypto.InitializeRequest
	(*InitializeResponse)(nil),              // 4: icrypto.InitializeResponse
	(*FinalizeRequest)(nil),                 // 5: icrypto.FinalizeRequest
	(*FinalizeResponse)(nil),                // 6: icrypto.FinalizeResponse
	(*ActivationDRMHandshakeRequest)(nil),   // 7: icrypto.ActivationDRMHandshakeRequest
	(*ActivationDRMHandshakeResponse)(nil),  // 8: icrypto.ActivationDRMHandshakeResponse
	(*ActivationDRMProcessRequest)(nil),     // 9: icrypto.ActivationDRMProcessRequest
	(*ActivationDRMProcessResponse)(nil),    // 10: icrypto.ActivationDRMProcessResponse
	(*ActivationDRMSignatureRequest)(nil),   // 11: icrypto.ActivationDRMSignatureRequest
	(*ActivationDRMSignatureResponse)(nil),  // 12: icrypto.ActivationDRMSignatureResponse
	(*ActivationDeprecatedRequest)(nil),     // 13: icrypto.ActivationDeprecatedRequest
	(*ActivationDeprecatedResponse)(nil),    // 14: icrypto.ActivationDeprecatedResponse
	(*ActivationRecordRequest)(nil),         // 15: icrypto.ActivationRecordRequest
	(*ActivationRecordResponse)(nil),        // 16: icrypto.ActivationRecordResponse
	(*ADIStartProvisioningRequest)(nil),     // 17: icrypto.ADIStartProvisioningRequest
	(*ADIStartProvisioningResponse)(nil),    // 18: icrypto.ADIStartProvisioningResponse
	(*ADIEndProvisioningRequest)(nil),       // 19: icrypto.ADIEndProvisioningRequest
	(*ADIEndProvisioningResponse)(nil),      // 20: icrypto.ADIEndProvisioningResponse
	(*ADIGenerateLoginCodeRequest)(nil),     // 21: icrypto.ADIGenerateLoginCodeRequest
	(*ADIGenerateLoginCodeResponse)(nil),    // 22: icrypto.ADIGenerateLoginCodeResponse
	(*AbsintheHelloRequest)(nil),            // 23: icrypto.AbsintheHelloRequest
	(*AbsintheHelloResponse)(nil),           // 24: icrypto.AbsintheHelloResponse
	(*AbsintheAddOptionRequest)(nil),        // 25: icrypto.AbsintheAddOptionRequest
	(*AbsintheAddOptionResponse)(nil),       // 26: icrypto.AbsintheAddOptionResponse
	(*AbsintheActivateSessionRequest)(nil),  // 27: icrypto.AbsintheActivateSessionRequest
	(*AbsintheActivateSessionResponse)(nil), // 28: icrypto.AbsintheActivateSessionResponse
	(*AbsintheSignDataRequest)(nil),         // 29: icrypto.AbsintheSignDataRequest
	(*AbsintheSignDataResponse)(nil),        // 30: icrypto.AbsintheSignDataResponse
	(*IdentitySessionRequest)(nil),          // 31: icrypto.IdentitySessionRequest
	(*IdentitySessionResponse)(nil),         // 32: icrypto.IdentitySessionResponse
	(*IdentityValidationRequest)(nil),       // 33: icrypto.IdentityValidationRequest
	(*IdentityValidationResponse)(nil),      // 34: icrypto.IdentityValidationResponse
	(*SAPExchangeRequest)(nil),              // 35: icrypto.SAPExchangeRequest
	(*SAPExchangeResponse)(nil),             // 36: icrypto.SAPExchangeResponse
	(*SAPSignPrimeRequest)(nil),             // 37: icrypto.SAPSignPrimeRequest
	(*SAPSignPrimeResponse)(nil),            // 38: icrypto.SAPSignPrimeResponse
	(*SAPVerifyPrimeRequest)(nil),           // 39: icrypto.SAPVerifyPrimeRequest
	(*SAPVerifyPrimeResponse)(nil),          // 40: icrypto.SAPVerifyPrimeResponse
	(*SAPSignRequest)(nil),                  // 41: icrypto.SAPSignRequest
	(*SAPSignResponse)(nil),                 // 42: icrypto.SAPSignResponse
	(*SAPVerifyRequest)(nil),                // 43: icrypto.SAPVerifyRequest
	(*SAPVerifyResponse)(nil),               // 44: icrypto.SAPVerifyResponse
}
var file_crypto_proto_depIdxs = []int32{
	0,  // 0: icrypto.Device.os_type:type_name -> icrypto.OSEnum
	1,  // 1: icrypto.InitializeRequest.type:type_name -> icrypto.InitializeType
	2,  // 2: icrypto.InitializeRequest.device:type_name -> icrypto.Device
	2,  // 3: icrypto.InitializeResponse.device:type_name -> icrypto.Device
	3,  // 4: icrypto.CryptService.Initialize:input_type -> icrypto.InitializeRequest
	5,  // 5: icrypto.CryptService.Finalize:input_type -> icrypto.FinalizeRequest
	7,  // 6: icrypto.CryptService.ActivationDRMHandshake:input_type -> icrypto.ActivationDRMHandshakeRequest
	9,  // 7: icrypto.CryptService.ActivationDRMProcess:input_type -> icrypto.ActivationDRMProcessRequest
	11, // 8: icrypto.CryptService.ActivationDRMSignature:input_type -> icrypto.ActivationDRMSignatureRequest
	13, // 9: icrypto.CryptService.ActivationDeprecated:input_type -> icrypto.ActivationDeprecatedRequest
	15, // 10: icrypto.CryptService.ActivationRecord:input_type -> icrypto.ActivationRecordRequest
	17, // 11: icrypto.CryptService.ADIStartProvisioning:input_type -> icrypto.ADIStartProvisioningRequest
	19, // 12: icrypto.CryptService.ADIEndProvisioning:input_type -> icrypto.ADIEndProvisioningRequest
	21, // 13: icrypto.CryptService.ADIGenerateLoginCode:input_type -> icrypto.ADIGenerateLoginCodeRequest
	23, // 14: icrypto.CryptService.AbsintheHello:input_type -> icrypto.AbsintheHelloRequest
	25, // 15: icrypto.CryptService.AbsintheAddOption:input_type -> icrypto.AbsintheAddOptionRequest
	27, // 16: icrypto.CryptService.AbsintheActivateSession:input_type -> icrypto.AbsintheActivateSessionRequest
	29, // 17: icrypto.CryptService.AbsintheSignData:input_type -> icrypto.AbsintheSignDataRequest
	31, // 18: icrypto.CryptService.IdentitySession:input_type -> icrypto.IdentitySessionRequest
	33, // 19: icrypto.CryptService.IdentityValidation:input_type -> icrypto.IdentityValidationRequest
	35, // 20: icrypto.CryptService.SAPExchange:input_type -> icrypto.SAPExchangeRequest
	37, // 21: icrypto.CryptService.SAPSignPrime:input_type -> icrypto.SAPSignPrimeRequest
	39, // 22: icrypto.CryptService.SAPVerifyPrime:input_type -> icrypto.SAPVerifyPrimeRequest
	41, // 23: icrypto.CryptService.SAPSign:input_type -> icrypto.SAPSignRequest
	43, // 24: icrypto.CryptService.SAPVerify:input_type -> icrypto.SAPVerifyRequest
	4,  // 25: icrypto.CryptService.Initialize:output_type -> icrypto.InitializeResponse
	6,  // 26: icrypto.CryptService.Finalize:output_type -> icrypto.FinalizeResponse
	8,  // 27: icrypto.CryptService.ActivationDRMHandshake:output_type -> icrypto.ActivationDRMHandshakeResponse
	10, // 28: icrypto.CryptService.ActivationDRMProcess:output_type -> icrypto.ActivationDRMProcessResponse
	12, // 29: icrypto.CryptService.ActivationDRMSignature:output_type -> icrypto.ActivationDRMSignatureResponse
	14, // 30: icrypto.CryptService.ActivationDeprecated:output_type -> icrypto.ActivationDeprecatedResponse
	16, // 31: icrypto.CryptService.ActivationRecord:output_type -> icrypto.ActivationRecordResponse
	18, // 32: icrypto.CryptService.ADIStartProvisioning:output_type -> icrypto.ADIStartProvisioningResponse
	20, // 33: icrypto.CryptService.ADIEndProvisioning:output_type -> icrypto.ADIEndProvisioningResponse
	22, // 34: icrypto.CryptService.ADIGenerateLoginCode:output_type -> icrypto.ADIGenerateLoginCodeResponse
	24, // 35: icrypto.CryptService.AbsintheHello:output_type -> icrypto.AbsintheHelloResponse
	26, // 36: icrypto.CryptService.AbsintheAddOption:output_type -> icrypto.AbsintheAddOptionResponse
	28, // 37: icrypto.CryptService.AbsintheActivateSession:output_type -> icrypto.AbsintheActivateSessionResponse
	30, // 38: icrypto.CryptService.AbsintheSignData:output_type -> icrypto.AbsintheSignDataResponse
	32, // 39: icrypto.CryptService.IdentitySession:output_type -> icrypto.IdentitySessionResponse
	34, // 40: icrypto.CryptService.IdentityValidation:output_type -> icrypto.IdentityValidationResponse
	36, // 41: icrypto.CryptService.SAPExchange:output_type -> icrypto.SAPExchangeResponse
	38, // 42: icrypto.CryptService.SAPSignPrime:output_type -> icrypto.SAPSignPrimeResponse
	40, // 43: icrypto.CryptService.SAPVerifyPrime:output_type -> icrypto.SAPVerifyPrimeResponse
	42, // 44: icrypto.CryptService.SAPSign:output_type -> icrypto.SAPSignResponse
	44, // 45: icrypto.CryptService.SAPVerify:output_type -> icrypto.SAPVerifyResponse
	25, // [25:46] is the sub-list for method output_type
	4,  // [4:25] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_crypto_proto_init() }
func file_crypto_proto_init() {
	if File_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crypto_proto_rawDesc), len(file_crypto_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crypto_proto_goTypes,
		DependencyIndexes: file_crypto_proto_depIdxs,
		EnumInfos:         file_crypto_proto_enumTypes,
		MessageInfos:      file_crypto_proto_msgTypes,
	}.Build()
	File_crypto_proto = out.File
	file_crypto_proto_goTypes = nil
	file_crypto_proto_depIdxs = nil
}
